### ISSUE TITLE
runtime: fatal error: bad pointer in write barrier

### ISSUE THREAD

**Issue by mikioh** [golang/go#11689]
See http://build.golang.org/log/aafb6004d46f88ffe84788b31f51d64bcef6d9b1.
```
runtime: writebarrierptr *0xc82b3ee008 = 0x3
fatal error: bad pointer in write barrier

runtime stack:
runtime.throw(0x5d2e80, 0x1c)
	/tmp/workdir/go/src/runtime/panic.go:527 +0x96
runtime.writebarrierptr.func1()
	/tmp/workdir/go/src/runtime/mbarrier.go:133 +0xb3
runtime.systemstack(0xc820018000)
	/tmp/workdir/go/src/runtime/asm_amd64.s:262 +0x7c
runtime.mstart()
	/tmp/workdir/go/src/runtime/proc1.go:668

goroutine 20 [running]:
runtime.systemstack_switch()
	/tmp/workdir/go/src/runtime/asm_amd64.s:216 fp=0xc8210711d0 sp=0xc8210711c8
runtime.writebarrierptr(0xc82b3ee008, 0x3)
	/tmp/workdir/go/src/runtime/mbarrier.go:134 +0x70 fp=0xc821071200 sp=0xc8210711d0
compress/flate.(*compressor).init(0xc820070240, 0xc8210481b0, 0x3, 0x9, 0x0, 0x0)
	/tmp/workdir/go/src/compress/flate/deflate.go:398 +0xdab fp=0xc821071398 sp=0xc821071200
compress/flate.NewWriter(0xc8210481b0, 0x3, 0x9, 0x0, 0x0, 0x0)
	/tmp/workdir/go/src/compress/flate/deflate.go:487 +0x64 fp=0xc8210713d8 sp=0xc821071398
compress/flate.testSync(0xc8210481b0, 0x3, 0xc82b414000, 0x0, 0x0, 0x5b00f0, 0xe)
	/tmp/workdir/go/src/compress/flate/deflate_test.go:458 +0xaf fp=0xc821071a60 sp=0xc8210713d8
compress/flate.testToFromWithLevelAndLimit(0xc8210481b0, 0x3, 0xc82b414000, 0x186a3, 0x188a3, 0x5b00f0, 0xe, 0xc7ce)
	/tmp/workdir/go/src/compress/flate/deflate_test.go:302 +0xac1 fp=0xc821071d10 sp=0xc821071a60
compress/flate.testToFromWithLimit(0xc8210481b0, 0xc82b414000, 0x186a3, 0x188a3, 0x5b00f0, 0xe, 0x186b2, 0xc5da, 0xc710, 0xc7ce, ...)
	/tmp/workdir/go/src/compress/flate/deflate_test.go:307 +0x83 fp=0xc821071d60 sp=0xc821071d10
compress/flate.TestDeflateInflateString(0xc8210481b0)
	/tmp/workdir/go/src/compress/flate/deflate_test.go:351 +0x256 fp=0xc821071f58 sp=0xc821071d60
testing.tRunner(0xc8210481b0, 0x6906f8)
	/tmp/workdir/go/src/testing/testing.go:455 +0x98 fp=0xc821071f90 sp=0xc821071f58
runtime.goexit()
	/tmp/workdir/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc821071f98 sp=0xc821071f90
created by testing.RunTests
	/tmp/workdir/go/src/testing/testing.go:560 +0x86d

goroutine 1 [chan receive]:
testing.RunTests(0x5f9d50, 0x690680, 0x12, 0x12, 0x80067d001)
	/tmp/workdir/go/src/testing/testing.go:561 +0x8ad
testing.(*M).Run(0xc82004cf08, 0x1a000)
	/tmp/workdir/go/src/testing/testing.go:493 +0x70
main.main()
	compress/flate/_test/_testmain.go:160 +0x116
FAIL	compress/flate	0.092s
```

**Comment by mikioh** [comment]
/cc aclements

#10603 happend again.

**Comment by ianlancetaylor** [comment]
CC @RLH

**Comment by spetrovic77** [comment]
I'm seeing the exact same problem when running Go on android.  It's easily reproducible, though the setup is quite complicated.

**Comment by rsc** [comment]
This is a write barrier being called to write 3 to the slot:

	runtime.writebarrierptr(0xc82b3ee008, 0x3)
		/tmp/workdir/go/src/runtime/mbarrier.go:134 +0x70 fp=0xc821071200 sp=0xc8210711d0

Because init was called with an io.Writer interface holding a 3 instead of a pointer:

	compress/flate.(*compressor).init(0xc820070240, 0xc8210481b0, 0x3, 0x9, 0x0, 0x0)
		/tmp/workdir/go/src/compress/flate/deflate.go:398 +0xdab fp=0xc821071398 sp=0xc821071200

Because NewWriter was called with that same io.Writer (and level = 9):

	compress/flate.NewWriter(0xc8210481b0, 0x3, 0x9, 0x0, 0x0, 0x0)
		/tmp/workdir/go/src/compress/flate/deflate.go:487 +0x64 fp=0xc8210713d8 sp=0xc821071398

But testSync was called with t=0xc8210481b0 and level=0x3:

	compress/flate.testSync(0xc8210481b0, 0x3, 0xc82b414000, 0x0, 0x0, 0x5b00f0, 0xe)
		/tmp/workdir/go/src/compress/flate/deflate_test.go:458 +0xaf fp=0xc821071a60 sp=0xc8210713d8
	compress/flate.testToFromWithLevelAndLimit(0xc8210481b0, 0x3, 0xc82b414000, 0x186a3, 0x188a3, 0x5b00f0, 0xe, 0xc7ce)
		/tmp/workdir/go/src/compress/flate/deflate_test.go:302 +0xac1 fp=0xc821071d10 sp=0xc821071a60

It is as if the (t, level) pair was copied directly to the NewWriter argument slots instead of the result of io.MultiWriter. Obviously the compiler isn't doing this all the time, or bad things would be happening.

Maybe a stack barrier at the wrong time, or a bad stack copy?

**Comment by rsc** [comment]
@spetrovic77 Can you post the full failure dump you get? I want to see how much the two have in common. Thanks.

**Comment by rsc** [comment]
And if you can make it happen repeatedly, posting three wouldn't hurt. Thanks.

**Comment by spetrovic77** [comment]
Sorry for the delay, here is the 1st stack:

 runtime: writebarrierptr *0x91f2ab60 = 0x1
 fatal error: bad pointer in write barrier

 runtime stack:
 runtime.throw(0xa2555bb8, 0x1c)
 	/usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/panic.go:527 +0x78
 runtime.writebarrierptr.func1()
 	/usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/mbarrier.go:120 +0xac
 runtime.systemstack(0x91c80a00)
 	/usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/asm_arm.s:239 +0x80
 runtime.mstart()
 	/usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/proc1.go:668
 
 goroutine 553 [running, locked to thread]:
 runtime.systemstack_switch()
	/usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/asm_arm.s:187 +0x4 fp=0x920651c4 sp=0x920651c0
 runtime.writebarrierptr(0x91f2ab60, 0x1)
 	/usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/mbarrier.go:121 +0x74 fp=0x920651dc sp=0x920651c4
 v.io/x/jni/util.jArg(0xb4aed1c0, 0xa23c9870, 0x91f2ab58, 0x91d22760, 0x12, 0x9218eda0, 0x920b3f01)

**Comment by spetrovic77** [comment]
2nd stack:

runtime: writebarrierptr *0x91ce4ec8 = 0x21
fatal error: bad pointer in write barrier

runtime stack:
runtime.throw(0xa2555bb8, 0x1c)
  /usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/panic.go:527 +0x78
runtime.writebarrierptr.func1()
  /usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/mbarrier.go:120 +0xac
runtime.systemstack(0xaeb01d48)
  /usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/asm_arm.s:239 +0x80
runtime.mstart()
  /usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/proc1.go:668

goroutine 638 [running, locked to thread]:
runtime.systemstack_switch()
  /usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/asm_arm.s:187 +0x4 fp=0x920d7118 sp=0x920d7114
runtime.writebarrierptr(0x91ce4ec8, 0x21)
   /usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/mbarrier.go:121 +0x74 fp=0x920d7130 sp=0x920d7118
v.io/x/jni/util.jArg(0xaec28940, 0xa23be978, 0x920e05c0, 0x91d36160, 0x2, 0x920d73ac, 0x92124fe0)

**Comment by spetrovic77** [comment]
3rd stack:

 runtime: writebarrierptr *0x91f9cb10 = 0x29
 fatal error: bad pointer in write barrier

 runtime stack:
 runtime.throw(0xa2555bb8, 0x1c)
   /usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/panic.go:527 +0x78
 runtime.writebarrierptr.func1()
   /usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/mbarrier.go:120 +0xac
 runtime.systemstack(0xaf1d1914)
   /usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/asm_arm.s:239 +0x80
 runtime.mstart()
   /usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/proc1.go:668

 goroutine 453 [running, locked to thread]:
 runtime.systemstack_switch()
   /usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/asm_arm.s:187 +0x4 fp=0x91edc83c sp=0x91edc838
 runtime.writebarrierptr(0x91f9cb10, 0x29)
   /usr/local/google/home/spetrovic/vanadium/third_party/android/go/src/runtime/mbarrier.go:121 +0x74 fp=0x91edc854 sp=0x91edc83c
 v.io/x/jni/util.jArg(0xb4b11040, 0xa23be978, 0x91d4fed0, 0x91d28130, 0x2, 0x91edcad0, 0x91fe6340)

**Comment by spetrovic77** [comment]
I forgot to mention, my Go client is synced to: cc6554f750ccaf63bcdcc478b2a60d71ca76d342.  The problem persists @ head for me, let me know if you want those stacks.  (I should have sent those stacks instead...)

**Comment by aclements** [comment]
> v.io/x/jni/util.jArg

There's a huge amount of unsafe code in this function. It's more likely that the bad write barrier in this case is the fault of jArg, and not the same cause as the original report.

**Comment by spetrovic77** [comment]
True, this is probably our fault.  We'll look into it.

**Comment by aclements** [comment]
Here are the occurrences of "bad pointer in write barrier" over the past month. I haven't looked at these to see if they look at all related, and the other two were before some memory corruption fixes (8c3533c and cc8f544).

[2015-06-28T21:41:38-d0ed87d/openbsd-amd64-gce56](http://build.golang.org/log/b48ddaba2a9ae1ff9cc537351ae2224330c7c597)
[2015-07-01T16:10:38-596ddf4/nacl-arm-cheney](http://build.golang.org/log/fc0a592e34a983d1c432788dd3d6ddfa36638e7d)
[2015-07-11T07:02:57-d5004ee/freebsd-amd64-gce101](http://build.golang.org/log/aafb6004d46f88ffe84788b31f51d64bcef6d9b1)

**Comment by rsc** [comment]
2015-06-28T21:41:38-d0ed87d/openbsd-amd64-gce56 looks like map corruption.
2015-07-01T16:10:38-596ddf4/nacl-arm-cheney looks like the old cmd/link death, now fixed.
2015-07-11T07:02:57-d5004ee/freebsd-amd64-gce101 is this one, with the magically reverted arguments.

I don't see any links here. Possibly the map bug is related to the one we can reproduce on nacl, or possibly not. I suspect the nacl-arm cmd/link bug is fixed. And this one hasn't happened again, so I am going to assume it is fixed or hibernating until we have evidence otherwise.

**Comment by davecheney** [comment]
I've been trying to get the nacl/arm builder back online, spoiler alert,
the build is not passing.

I tried updating to pepper44 yesterday without luck, I'll dump what I know
so far into an issue.

**Comment by balboah** [comment]
No idea on how to reproduce but got this on gomobile for android:
```
Go  E  runtime: writebarrierptr *0x67a39d4c = 0x68686868
05-11 09:51:19.314   8537     8606                               Go  E  fatal error: bad pointer in write barrier
05-11 09:51:19.324   8537     8606                               Go  E  runtime stack:
05-11 09:51:19.324   8537     8606                               Go  E  runtime.throw(0x571ac710, 0x1c)
05-11 09:51:19.324   8537     8606                               Go  E  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:547 +0x80
05-11 09:51:19.324   8537     8606                               Go  E  runtime.writebarrierptr.func1()
05-11 09:51:19.324   8537     8606                               Go  E  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/mbarrier.go:140 +0xb4
05-11 09:51:19.324   8537     8606                               Go  E  runtime.systemstack(0x57373800)
05-11 09:51:19.324   8537     8606                               Go  E  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_arm.s:247 +0x8c
05-11 09:51:19.324   8537     8606                               Go  E  runtime.mstart()
05-11 09:51:19.324   8537     8606                               Go  E  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/proc.go:1051
05-11 09:51:19.324   8537     8606                               Go  E  goroutine 1 [running, locked to thread]:
05-11 09:51:19.324   8537     8606                               Go  E  runtime.systemstack_switch()
05-11 09:51:19.324   8537     8606                               Go  E  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/asm_arm.s:192 +0x4 fp=0x67a39c54 sp=0x67a39c50
05-11 09:51:19.324   8537     8606                               Go  E  runtime.writebarrierptr(0x67a39d4c, 0x68686868)
05-11 09:51:19.324   8537     8606                               Go  E  /usr/local/Cellar/go/1.6.2/libexec/src/runtime/mbarrier.go:141 +0xa4 fp=0x67a39c6c sp=0x67a39c54
05-11 09:51:19.324   8537     8606                               Go  E  github.com/google/gopacket/layers.init.1()
05-11 09:51:19.324   8537     8606                               Go  E  /Users/kargs/code/go/src/github.com/google/gopacket/layers/enums.go:381 +0x4dc fp=0x67a39e70 sp=0x67a39c6c
05-11 09:51:19.324   8537     8606                               Go  E  github.com/google/gopacket/layers.init()
05-11 09:51:19.324   8537     8606                               Go  E  /Users/kargs/code/go/src/github.com/google/gopacket/layers/usb.go:308 +0x74c8 fp=0x67a39f4c sp=0x67a39e70
```

**Comment by aclements** [comment]
Hi @balboah. Since this issue is already considered closed, please open a new issue. You can reference this issue from the new issue if you think it's related.

**Comment by quentinmit** [comment]
Pinging this bug; @balboah's dupe #15831 seems like it could be evidence the bug is still there.

**Comment by mikioh** [comment]
@quentinmit, I think it's better to ping @aclements on #15831.

**Comment by aclements** [comment]
#15831 is unlikely to be related to this bug. (Lots of things can lead to "bad pointer in write barrier". Usually it means that something somewhere conjured a non-pointer into a pointer and then it got passed to the write barrier. The write barrier catches it, but it's not the write barrier's fault.)
