### ISSUE TITLE
reflect: add a function for treating C memory as a Go slice

### ISSUE THREAD

**Issue by bcmills** [golang/go#13656]
Now that cgo supports exporting Go functions to C, it would be useful for Go functions to be able to read C memory without making unnecessary copies.  In particular, we would like to be able to read (and write) a C `char*` using functions that operate on a Go `[]byte` (e.g. `bytes.Reader` or `io.Reader.Read`).

`reflect.NewAt` and `reflect.ArrayOf` get us partway there: we can treat the pointer to C memory as a Go pointer to an array of the correct underlying length, then use `reflect.Value.Slice` to convert that to a slice.  Unfortunately, `reflect.ArrayOf` strands a small amount of memory for a unique `reflect.Type` for every distinct length used: http://play.golang.org/p/lc3QnMnKP_

We could consider using `reflect.SliceHeader` instead, but it "cannot be used safely or portably" (https://golang.org/pkg/reflect/#SliceHeader).

So it seems that we don't have an efficient solution for this conversion.

The simplest solution seems like it would be to add a function to the `reflect` package to construct the slice directly.  Following the example of `reflect.MakeSlice` and `reflect.NewAt`, it could be something like:

``` go
    // SliceAt returns a slice value for the specified slice type, length, and capacity,
    // using p as the address of the first element and leaving its contents unchanged.
    func SliceAt(typ Type, len, cap int, p unsafe.Pointer) Value
```

**Comment by minux** [comment]
We already have C.GoBytes that converts a unsafe.Pointer
and a length to []byte, why do we need another?

After converting the pointer to a byte slice, it's very easy
to convert to []T for arbitrary T.

**Comment by bcmills** [comment]
> We already have C.GoBytes that converts a unsafe.Pointer
> and a length to []byte, why do we need another?

1) My understanding was that C.GoBytes makes a copy.  Is that not the case?
(If correct, that implies less efficiency - particularly for large arrays - and no mutative APIs such as io.Reader.Read.)
 
2) It doesn't work for element types other than byte.  (For example, you could envision a C API that wants to use an array of wchar_t or uint32_t.)

> After converting the pointer to a byte slice, it's very easy to convert to []T for arbitrary T.

Not without copying the underlying array.  Or am I missing something?

**Comment by minux** [comment]
You can convert a unsafe.Pointer p to any []T without copying
as follows:
    (*[(1 << 31) / unsafe.Sizeof(T{})]T)(p)[:len:len]

**Comment by bcmills** [comment]
That isn't portable: on 64-bit platforms it only expresses sizes up to 2GB.  (And you can't work around it by increasing the constant because then it doesn't work on 32-bit platforms.)

It also seems likely to interact poorly with analysis tools: it temporarily produces a pointer to an "array" with elements in invalid memory.

**Comment by minux** [comment]
There is way to use correct cap on all platforms:
(*[1<<(^uint(0)>>27&63)/unsafe.Sizeof(T{}) - 1]T)(p)[:len:len]

If the code breaks some analysis tool, then it's a
bug of the analysis tool. The code is fully conforming
and portable. If p is not pointing to Go heap, it should
also work with future GC enhancements.

**Comment by bcmills** [comment]
1) Expecting CGo users in general to come up with those constants on their own is fairly user-hostile, when we could just provide a function that does it correctly.

2) Where in the spec does it say that pointers to arrays with arbitrary lengths are valid?  gc is not the spec, and gc is also not the only Go implementation.  (One could easily envision a compiler that, say, sanity-checks that all pointers to arrays point to addresses that are mapped in the program's address space.)

**Comment by bcmills** [comment]
Also, those constants aren't even correct on amd64:

`$ cat test/foo.go`
```go
package main

import (
        "fmt"
        "reflect"
        "unsafe"
)

func main() {
        s := []byte("Hello, ⚛")
        n := len(s)
        p := reflect.ValueOf(s).Pointer()

        s2 := (*[1<<(^uint(0)>>27&63)/unsafe.Sizeof([]byte{}) - 1]byte)(p)[:n:n]
        fmt.Println(string(s2))
}
```

```
$ go run test/foo.go
# command-line-arguments
test/foo.go:14: type [384307168202282324]byte larger than address space
test/foo.go:14: cannot convert p (type uintptr) to type *[384307168202282324]byte
```

That comes from here:
https://tip.golang.org/src/cmd/compile/internal/gc/align.go?h=address+space

To me, the fact that even you - someone deeply familiar with the Go language and its implementations - couldn't get those constants right strongly suggests that we should not expect more casual cgo users to do so.

**Comment by randall77** [comment]
I agree that we should probably find a solution to this problem.  We want to make cgo easier & safer.

Using SliceHeader is ok, that "cannot be used safely" warning is aimed at people trying to store Go pointers in its Data field.  Storing C pointers in the Data field should be ok.  The rest of the warning is basically the same as the one for unsafe.Pointer.
It's still tricky, though, you'd have to do:

    h := reflect.SliceHeader{uintptr(p), n, n}
    s := *(*[]T)(unsafe.Pointer(&h))

(In an ideal world, SliceHeader.Data should be an unsafe.Pointer, not a uintptr.  Too late now.)

I'm hesitant to put the fix in reflect, it is too heavyweight.  Maybe just something in package unsafe?

    // MakeSlice makes a slice out of ptr/len/cap and stores it to s.
    func MakeSlice(s, ptr unsafe.Pointer, len, cap int)

**Comment by bcmills** [comment]
> Using SliceHeader is ok, that "cannot be used safely" warning is aimed at people trying to store Go pointers in its Data field.  Storing C pointers in the Data field should be ok.

If that's the case, then just a doc fix might be sufficient.  (I suggested a similar approach in some code I was reviewing and @ianlancetaylor said not to do it.)

> I'm hesitant to put the fix in reflect, it is too heavyweight. Maybe just something in package unsafe?

Maybe?  But unsafe doesn't otherwise have anything to do with built-in data structures like slices, and it's not entirely clear to me how you'd get from that to a value of slice type.  Would you convert "s" to a pointer-to-slice, or to some other type (e.g. the slice itself)?  If it's a pointer-to-slice, is the slice header allocated on the Go heap?

reflect.Value.Interface() at least makes the answers to those questions consistent, which is why it seems like a more natural fit to me - and `SliceAt` isn't that far off from the existing `reflect.MakeSlice` and `reflect.NewAt`.

**Comment by bcmills** [comment]
In particular, this snippet of existing `reflect` code would be equivalent to `SliceAt` modulo the memory leakage for the `reflect.ArrayOf` call:
 
```go
    func SliceAt(typ reflect.Type, len, cap int, p unsafe.Pointer) reflect.Value {
      return reflect.NewAt(reflect.ArrayOf(len, typ.Elem()), p).Elem().Slice(0, len)
    }
```

**Comment by randall77** [comment]
You'd do something like this:

    var s []T
    unsafe.MakeSlice(unsafe.Pointer(&s), ptr, len, cap)
    ...use s...

Doing it this way gets around the polymorphic return type you would need if MakeSlice returned a slice, or the allocation you would need if MakeSlice returned an unsafe.Pointer to a slice.

I agree that this is functionality that unsafe hasn't had historically.  But I think it would be the right place for this operation.  On the other hand, reflect.NewAt has a similar feel, and maybe both it and MakeSlice should be together.

**Comment by ianlancetaylor** [comment]
I don't see how to use reflect.SliceHeader safely unless we exempt it from the Go 1 guarantee or promise that we will never change the representation of slices.  Since in the past we've discussed changing the representation of slices, it seems unwise to commit to the current representation for all time and for all implementations.  Same for reflect.StringHeader, of course.

**Comment by randall77** [comment]
To use reflect.SliceHeader you need to use unsafe, and unsafe is exempt from the Go 1 guarantee.

**Comment by oec** [comment]
FWIW, this is not just a cgo related issue, it already occurs in some of the syscal-wrappers. For example, an implementation of syscall.Mmap needs to do basically the same construction.  It would be helpful if there is an API - even under unsafe - available that hides the implementation details and memory-layout for slices away. (Assuming the API doesn't need to change or can be augmented with an refined version).

**Comment by rsc** [comment]
This doesn't seem exactly what reflect is for. And it's not specific to cgo either: this comes up in system calls like mmap. I could see possibly adding something like unsafe.Slice(p, n, m) with the right types (p is pointer to T, result is []T). That would be a language change.

I guess we could add reflect.UnsafeSlice(t, p, n, m) to return an interface{} or a Value holding a slice of type t with pointer p, len n, cap m. It's not really reflect but maybe it's fine. I guess it's more reflect than Swapper, although that's not a great argument.

Personally, I don't mind writing `*(*[1<<30]T)(unsafe.Pointer(p))[:n:m]`.

**Comment by rsc** [comment]
I think it's too late to do this for Go 1.8 at least.

**Comment by bradfitz** [comment]
@bcmills, are you still interested in this?

**Comment by bcmills** [comment]
Yes.  (But I'm not sure whether I'll have the bandwidth to implement it for 1.9.)

**Comment by oec** [comment]
I'm interested, too, and it looks like I have the time until May to try and implement unsafe.Slice(p, n, m), as suggested by Russ.

**Comment by oec** [comment]
@rsc, you mention "*(*[1<<30]T)(unsafe.Pointer(p))[:n:m]", which I would consider acceptable as well.  However, the _current_ limit on the ArrayLength in the declaration of an array does not allow for sizes larger than 1<<30, even on 64-bit, which breaks your approach when the data pointed to is larger than 2GB (like, when calling mmap on large files).  Wouldn't it make sense to change that current limit for ArrayLength on 64-bit platforms, instead of (or in addition to) adding an API for slice-creation?

**Comment by ianlancetaylor** [comment]
The current limit on array size on amd64 is `1 << 50` bytes.  You can handle memory blocks larger than 2G.

Probably we should permit larger values for pointer to array types.

**Comment by oec** [comment]
I wasn't aware of the distinction between [N]T and *[N]T regarding N, interesting.  Is it safe to assume that allowing values up to N==1<<50 for *[N]T is easier to implement than adding an unsafe.Slice(p, n, m) API?

**Comment by bcmills** [comment]
It might be easier, but arguably the user experience is much worse.  See the discussion starting at https://github.com/golang/go/issues/13656#issuecomment-165618599.

**Comment by oec** [comment]
Don't get me wrong, I would like to see unsafe.Slice(p, n, m).  But until then I would be happy to use (*[N]T)(unsafe.Pointer(p))[:n:m] with large enough N, if this is cheap to get.  Right now, even that doesn't work for larger N.

**Comment by rsc** [comment]
For the record, I proposed reflect.UnsafeSlice not unsafe.Slice. We're not adding to unsafe - that's a language change.

**Comment by rsc** [comment]
Rereading, I guess I mentioned both, but the point here is that if we do something for Go 1.9 it needs to be in reflect.

**Comment by cespare** [comment]
@oec are you (or anyone else on this thread) still planning on sending a reflect.UnsafeSlice CL for 1.9? I'm also interested in this feature and would be happy to do the work.

**Comment by rsc** [comment]
I think I'd rather leave this for Go 1.10 at this point. reflect is pretty awful too - I forgot that you'd have to return an interface{} or a reflect.Value.

**Comment by ianlancetaylor** [comment]
@oec In case I wasn't clear `[1<<N]byte` already works today for constant `N` up to `50`.

**Comment by ianlancetaylor** [comment]
For the case of cgo we could implement this directly in cgo.

C.AsSlice(T, CPointer, Len)

That will evaluate to a `[]T` that points into C memory with `Len` elements (the slice length and capacity will both be set to `Len`).  Passing `T` directly is weird but should work, and I don't see a better way.

That won't help people who are using `mmap` directly, though.

**Comment by bcmills** [comment]
1.10 is probably fine for `reflect` or `unsafe`.  I like Ian's idea of adding a builtin for cgo: it nicely parallels `C.GoString`.  (So perhaps we should name it `C.GoSlice`?)

FWIW, I still think returning `reflect.Value` is the right thing for Go 1 due to the similarity to `reflect.NewAt` and `reflect.MakeSlice`.  At the very least, even if we did add to `unsafe` I think we would also need to add something to `reflect` too: presumably the `unsafe` variant would need at least one typed argument, so we'd be introducing an operation for concrete types that doesn't have a reflective equivalent.

**Comment by oec** [comment]
@cespare, please go ahead, I don't think I could come up with implementation under reflect. for 1.9 anyways (unsafe. sounds much simpler, but I might be wrong).

@ianlancetaylor, I think I understand correctly: [1<<50]byte, but only *[1<<30-1]byte, correct?

**Comment by ianlancetaylor** [comment]
@oec up to `50` should work in both forms on amd64.

**Comment by oec** [comment]
@ianlancetaylor, thanks for the clarification, this is (very good) news to me, I must have missed that change.   (But I think the error messages for other platforms (like nacl-amd64p32 as on play.golang.org) could be improved by stating "constant NNN overflows int *on this platform*" and "array bound is too large *on this platform*")

**Comment by bcmills** [comment]
@ianlancetaylor, coming back to your suggestion in https://github.com/golang/go/issues/13656#issuecomment-291947849.

I think we can omit the type argument: we can infer it from the type of the pointer. AsSlice would follow the type schema

```go
AsSlice(*T, int) []T
```

for any type T, and if you want to use it with an 'unsafe.Pointer' you'd have to first cast that pointer to a concrete type:

```go
var s []byte = C.AsSlice((*byte)(ptr), n)
```

**Comment by rsc** [comment]
It seems like this can't be done in reflect cleanly.

We could experiment with adding it to cgo, but we were also talking about passing the unmodified sources to the Go compiler and letting it do name lookups like C.foo. Adding a new "intrinsic" here would complicate that a little. 

The alternative is to put it in unsafe, which is a language change.

**Comment by rsc** [comment]
It's #19367 that I'm thinking of. That's on hold for Go 2, so probably this should be too. (That would address this exact need.)

**Comment by bcmills** [comment]
FWIW, I have implemented a library locally using `reflect` and based on the comments above.
Oddly, it appears that `reflect` does not enforce the same limits on array sizes as the compiler.

My solution for `reflect` would be roughly:

```go
// SliceAt returns a view of the memory at p as a slice of elem.
// The elem parameter is the element type of the slice, not the complete slice type.
func SliceAt(elem Type, p unsafe.Pointer, n int) Value {
	return NewAt(bigArrayOf(elem), p).Elem().Slice3(0, n, n)
}

// bigArrayOf returns the type of a maximally-sized array of t.
//
// This works around the memory-stranding issue described in
// https://golang.org/issue/13656 by producing only one array type per element
// type (instead of one array type per length).
func bigArrayOf(t Type) Type {
	n := ^uintptr(0) / uintptr(t.Size())
	const maxInt = uintptr(^uint(0) >> 1)
	if n > maxInt {
		n = maxInt
	}
	return ArrayOf(int(n), t)
}
```

**Comment by jimmyfrasche** [comment]
The problem is having to write `(*[C]T)(unsafe.Pointer(v))[:n:n]`, for some `C`, `T`, `v`, and `n`.

A simpler way to write that entire expression would be ideal.

If that can't be fixed before Go2, perhaps an easier problem could be.

A lot of people much smarter than I am have written the constant `C` many different ways in this thread. It's the most magic part of the expression and the part that I am the least confident I am writing (well, copy-and-pasting) correctly.

If cgo (or runtime or somewhere appropriate) exported a constant with the correct value of `C` that is the largest possible `C` for the current platform that would, at least, make it easier to write portable, correct code.

I would much rather a solution to the whole problem be found and am only suggesting this if there is no better solution that can be implemented before Go2.

**Comment by ianlancetaylor** [comment]
@jimmyfrasche It's an interesting idea but the maximum value for `C` depends on the size of `T`.

**Comment by jimmyfrasche** [comment]
@ianlancetaylor if it's the maximum for the platform assuming a size of 1 you could use it to compute the correct value for arbitrary T. Still not pretty and far from ideal, but its use could be documented and explained on the wiki (which currently just has 1 << 30 without explanation now https://github.com/golang/go/wiki/cgo#turning-c-arrays-into-go-slices )

**Comment by rsc** [comment]
Going to close this since it seems clear that anything we do in reflect is going to be awful. Better to wait for #19367.

**Comment by gobwas** [comment]
Hi @rsc @ianlancetaylor, I am also curious about the specification of the GC behavior when it does not interacts with slices/strings which `Data` field points to the C-allocated memory.

I have only found [this paragraph](https://github.com/golang/go/wiki/cgo#turning-c-arrays-into-go-slices) from the cgo wiki.

This question relates this comment by @bcmills :
> Where in the spec does it say that pointers to arrays with arbitrary lengths are valid? gc is not the spec, and gc is also not the only Go implementation. (One could easily envision a compiler that, say, sanity-checks that all pointers to arrays point to addresses that are mapped in the program's address space.)

Thanks!
