### ISSUE TITLE
golang-nuts - banned?

### ISSUE THREAD

**Issue by liamstask** [golang/go#13819]
My apologies for the off topic issue, but since I can't post to golang-nuts I was not sure where else to raise this.

I appear to have been banned from the golang-nuts group, but am not sure why. Is it possible to clarify why, or possibly reinstate my membership? It would have been through my google account `lstask@gmail.com`, with an additional email address `liam@stask.net`

Thanks.

<img width="512" alt="screenshot" src="https://cloud.githubusercontent.com/assets/51256/12102637/f63417c4-b2f0-11e5-95c8-82cae2b3b7e6.png">

**Comment by bradfitz** [comment]
I'm a moderator of that group but I see neither of those two email addresses listed as being either a member or banned.

Try joining the group first?

**Comment by liamstask** [comment]
thanks for the quick response. i wonder if my membership is in some kind of broken state.
* in response to an empty mail sent to `golang-nuts+subscribe@googlegroups.com` I get
    ```
Hello liam@stask.net,

The group you attempted to subscribe to is invite only.  You must be invited by the group owner.

If you have questions related to this or any other Google Group, visit the Help Center at https://groups.google.com/support/.

Thanks,

Google Groups
```
* there is no `join group` button when I visit https://groups.google.com/forum/#!forum/golang-nuts
* when I click `new topic` it takes me to the compose view, and when I try to change my display name (just to try), I see the following prompt and clicking on `join group to change` has no effect
<img width="512" alt="screenshot" src="https://cloud.githubusercontent.com/assets/51256/12103051/22f7271c-b2f4-11e5-9ca2-eb935bbb501e.png">
* when I try to post a test msg via the web UI, I get `You do not have permission to access this content. (#554)`

**Comment by bradfitz** [comment]
Well, I tried to invite you and I got:

```
No new invitations were sent
One person has been banned from the group
lstask@gmail.com
```

So, I guess you are banned. Let me try to figure out this UI enough to see where.

**Comment by bradfitz** [comment]
Unfortunately

a) you did get banned somehow
b) the Google Groups interface makes fixing this close to impossible

We have 55,511 banned members at https://groups.google.com/forum/#!managemembers/golang-nuts/members/banned

But there's no search over them and I can only go through the list one page at a time. See https://productforums.google.com/forum/#!category-topic/Apps/LEt9s3tHecE for other people complaining about this.

**Comment by bradfitz** [comment]
It looks like maybe there's an API for Google Groups? Is it https://developers.google.com/admin-sdk/directory/v1/guides/manage-groups ? Maybe we can use that to write a tool to fix this.

/cc @ianlancetaylor @adg

**Comment by adg** [comment]
The trick is to edit the search URL (`s/active/banned`) to search the banned user list:

https://groups.google.com/forum/#!managemembers/golang-nuts/members/banned/filter:liam@stask.net

I unbanned liam@stask.net. I'll close this issue assuming the problem is resolved.

**Comment by liamstask** [comment]
thank you.

i sent an email with a new topic from `liam@stask.net` and didn't see it show up in the web ui after ~30-40 minutes, so tried posting from the web ui, and got feedback that my topic would be posted after it was approved (wasn't able to grab a screenshot of the specific language used).

so, assuming the msg actually shows up at some point, it appears to be all good - hoping this first msg (which might now be a double post) is just subject to additional moderation.

**Comment by adg** [comment]
I just approved your post (and deleted the duplicate). Your future posts
should go through without need for approval.

**Comment by liamstask** [comment]
thanks again.

**Comment by liamstask** [comment]
i think there's still a problem (sorry) :/

follow up posts to the original msg submitted via email (liam@stask.net) are not showing up in the web ui (though I am receiving other posts to the list on that address).

posting via the web ui results in an initial successful response, and then the message shows up as `deleted` in the [discussion thread](https://groups.google.com/forum/#!topic/golang-nuts/SYPHeKP84X4) (my two attempts show as deleted there for me).

any suggestions? maybe `lstask@gmail.com` also needs to be unbanned, since that address is also associated with my google account?

**Comment by ianlancetaylor** [comment]
Your replies were marked as spam, and therefore were waiting for moderator approval.  I approved one of them.

**Comment by liamstask** [comment]
gah, ok. thanks again, and sorry for the noise.
