### ISSUE TITLE
cmd/compile: support inlining non-escaping closures

### ISSUE THREAD

**Issue by josharian** [golang/go#15561]
Split out from #9337 and #15537.

**Comment by rogpeppe** [comment]
I'd very much like to see this happen. An idiom that's useful for dealing with lots of returns from a function with long-winded return values is this:

	func f() (int, int, error) {
		fail := func(err error) (int, int, error) {
			return 0, 0, err
		}
		if somethingWrong {
			return fail(someError)
		}
		return foo, bar, nil
	}

It would be great if this generated exactly the same code as the equivalent:

	func f() (int, int, error) {
		if somethingWrong {
			return 0, 0, someError
		}
		return foo, bar, nil
	}

**Comment by thepudds** [comment]
Hi @rogpeppe, is your specific request in https://github.com/golang/go/issues/15561#issuecomment-272143119 addressed at this point, or still pending?

For your example, it looks like `fail` gets inlined, but `f` does not (`cannot inline f: unhandled op CLOSURE`), but I'm not sure which piece you personally were focused on in your example. 

Separately, I'm not sure sure if this overall issue is about addressing inlining `fail` in this example, or `f`, or both.

```
func f() (int, int, error) {
	fail := func(err error) (int, int, error) {
		return 0, 0, err
	}
	if somethingWrong {
		return fail(someError)
	}
	return foo, bar, nil
}
```

(And sorry, I just looked at a bunch of examples, so non-trivial chance I might just be confused here).

**Comment by DmitriyMV** [comment]
This appears to be fixed on the latest Go

@josharian @rogpeppe am I correct?

**Comment by fice-t** [comment]
One thing remaining for this issue is that the closure definition is not trimmed from the function if there are no remaining uses after inlining. See this [godbolt example](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyahg6cisaoiBIdWaYAwunoBXNkxAAmLeQcAZAiZsADl3ACNsUhAAZnIAB3QlYlsmZzcPA0TkmyFA4LC2SOi4y2xrVJEiFlIidPdPHwtsK1ymKpqifNCIqNiLatr6zJ4Bzu7C4tiASgt0V1JUTi54llQAaxZgbABqeIBSLQBBQ6OANxqdpXQOXFJSMh2oh9JT05pXJlQdmggAdx24XQLmmOwgQSI5B2EKhzzIoP2AHYAEJvLQAThoLAYOxA%2BxiABEfp9UBBnk97vCwTDocJYZTSAiUWj0Yd0aRsEQFkwdr5efTXsc2UiCSyCDQdgCkaihRi2RyuaQeViGBBrrcGdMWSKWQruTtRjsvFCmAw3oiCVxZvRuABWfieLg6cjobgAcXQV3mi12%2By8MT45CI2its3WIFtWgAdFppAGtF4AGy2gAcicR6MRtsM3Gk/DYEd8judrq4/CUIF8wadVvIcFgKAwOHwxDIlGodEYrA43EDgmEYgknBkcmEyjUmhr5H0xqMJhAZmarVS9iYThcDW82YCQR6RT6iISSRSQmGjWz2RPTAmvWih7KFSEHSGG8yXmzD7az66u8mB7GL4ZOeAE/gUt4gIiszXAsSzcKsGxbLsByyuclzqngDIUi8aJHB8Xw/P8gLAvQoLgnStKQlhVLSmKEpSsysqshiepKvybHoXc2GMTqjEsTyhrGjspr0OalrWnaDohi67qetBPo7H6MRePw1Y6NMsxINgLA4NEEDiVwebkAWkbkMW/CluWlZBiG6nkOGkYxnGPAJsmaYZlmOZcDEklThZ1k1rM9YIPAECNjc8QMFE7YQBgbARYw0TAPQNjxAIDBEFEFYQOEUnhEENQAJ69vweWsKQBUAPLhLo5TVoGsUcMIFVMPQRVTjg4SuMAjgSPQFa8PwOBsMYSXLM6hAchUZzYP1zrYOo5SuBlxWUMILRSfQBDhKQhXODgK1EKQBAFgN5DTaQQIqAS2DDSYm3zgFAhGMASgAGoENgfwVfEzArf2ojiJII7/eOGhSfooxzqY5ibeEFaQLM6DxG0/UALRsOZ51HTg8N6UutUrmSa5ngYO5gfu0SjJebQk1Tx5tDeFMGJ%2BlSDHUr6eKMLNPmzjNTFzbO0yBfN9DwUHerBYuefaplSaWOzqGmqOJtIOzAN8EApaRLYkKQCn%2BmLKk2XWKDzEQ8RLdFsXxVEITsMsiuJsrqvq2CWv8NghC6wQmAGP9g5A7IIMqGDU4Q%2BQfw7fExX6TLZnSVwFVLRbRA7OgEqO87asa1rYLOHFkV64phv%2BWpYYgNI6JRuitqJimmYxNIPBKS5nmGcZRZy9wllVsbQWhWg4WF1bQ8JQuyUEKlnYZaQWU5VOpWFSti/lVVNXWCtDXMEQzWtVJHVdT19B9StQ0jZI7UEJNNjTbNHsLagS3LIGELrVOsM7eVe1jSpR0nYG51LrYGurdJKQRQCPRoM9N6H0vo/UdH2eQAdhxB3kKDSczoZyGBGguGGW1caI2RqkfqmNng%2BxmvAKCLQCZ2CJuuICpM1wi0pkeHIqQhbU1SMw5m1DHztEFhzHhy4ebjF/OBAWnQhZKF5mIpmUs5KwS8LHHyJZuAKyVirbObtJ7ay9o8RSSijYBQ0lpHS1B9Lt0LLLXy3cLBWVUqGOyFcq41zrg3JuLckyeW8tY1RZZS6OJtFwZSvjzK2IcbZc6yQ7DSCAA%3D%3D) that shows the definition for `f.func1` still remaining.

**Comment by randall77** [comment]
The definition still existing is fine. If it is not referenced the linker will discard it.
