### ISSUE TITLE
x/build: delete tmp.shadams branch from build.golang.org

### ISSUE THREAD

**Issue by stemar94** [golang/go#21741]
Found this today:

tmp.shadams:
https://github.com/golang/go/tree/tmp.shadams
I think this one shouldn't be on remote/github.

**Update:**
q:
https://github.com/golang/go/tree/q
I think this one shouldn't be on github.

**Comment by davecheney** [comment]
And this one, https://github.com/golang/go/tree/q

**Comment by stemar94** [comment]
Previous case:
https://groups.google.com/forum/#!topic/golang-dev/EqqZf5kTRqI

**Comment by dsnet** [comment]
The branch `tmp.shadams` appears on the googlesource.com as well:
https://go.googlesource.com/go/+refs

**Comment by bcmills** [comment]
(CC: @adams-sarah)

**Comment by adams-sarah** [comment]
Hey sorry, I've been trying to debug https://github.com/golang/go/issues/21555 in spare moments w/ this branch.

@rsc and @aclements aware. But I'll just delete for now, as I don't have much spare time to work on this ATM.
It will appear again later though, when I have more time to debug.

**Comment by adams-sarah** [comment]
done

**Comment by rsc** [comment]
Added this to my .git/config:

```
[remote "github"]
	url = ssh://git@github.com/golang/go
	fetch = +refs/heads/*:refs/remotes/github/*
```

and then did this:

```
$ git fetch github
...
$ git push -d github q
To ssh://github.com/golang/go
 - [deleted]               q
$ git push -d github tmp.shadams
To ssh://github.com/golang/go
 - [deleted]               tmp.shadams
$ 
```

I think tmp.shadams came back quickly thereafter, but I deleted it again and at the moment it is still gone. If it comes back I'm not too worried - it can stay until Sarah is done debugging. "q" was clearly someone's mistyped command and it's gone and I don't expect it to return.

**Comment by rsc** [comment]
Not going crazy, tmp.shadams is back again but q is still gone. Will reopen and leave assigned to Sarah for when she's done debugging. No rush on this. The name makes clear what's going on.

**Comment by adams-sarah** [comment]
Huh weird. I deleted it from gerrit; figured the next push to gh would wipe it out.
tmp.shadams branch is not in gerrit ui nor does it appear on `git fetch` from origin (https://go.googlesource.com/go) anymore.

**Comment by stemar94** [comment]
I think this can be closed.

For anyone still seeing some branches:
```bash
git fetch --all --prune
```
Worked for me.

**Comment by adams-sarah** [comment]
hey @stemar94 thanks for your help :)
yea, so the branch is no longer in git nor remotes. but unfortunately it is still in the dropdown at the top of build.golang.org. i'm hoping to have time to fix this soon, it should just require some entities in Datastore to be deleted.

i'm going to re-open the issue for now, but i'll rename it so it's more clear what's going on.

**Comment by adams-sarah** [comment]
done. branch is gone from build.golang.org.
