### ISSUE TITLE
cmd/go: get must report implied upgrades/downgrades

### ISSUE THREAD

**Issue by bcmills** [golang/go#25917]
This is a followup to a [golang-nuts thread](https://groups.google.com/d/msg/golang-nuts/y3FtnVVfvcI/rjIYnpisBAAJ).

I can import an arbitrary version of the module `github.com/docker/docker` (which lacks a `go.mod` file at all tagged versions in its repo) by specifying the version in the `go.mod` file. However, at least as of vgo `0a6cdd7`, I can't obtain the same version using `vgo get` on one of the packages it contains.

```
/tmp/importdocker$ cat go.mod
module github.com/bcmills/importdocker

require github.com/docker/docker v1.13.1


/tmp/importdocker$ cat main.go
package main

import _ "github.com/docker/docker/client"

func main() {}


/tmp/importdocker$ vgo list -m | grep docker/docker
github.com/docker/docker                          v1.13.1
github.com/docker/docker-credential-helpers       v0.0.0-20160906164316-f72c04f1d8e7

/tmp/importdocker$ vgo get github.com/docker/docker/client@v17.05.0-ce
vgo: finding github.com/docker/docker/client v0.0.0-20170504205632-89658bed64c2
vgo: github.com/docker/docker/client v0.0.0-20170504205632-89658bed64c2: missing go.mod
vgo get: missing go.mod

/tmp/importdocker$ sed -i 's/v1.13.1/v17.05.0-ce/' go.mod

/tmp/importdocker$ vgo list -m | grep docker/docker
github.com/docker/docker                          v0.0.0-20170504205632-89658bed64c2
github.com/docker/docker-credential-helpers       v0.5.0
```

**Comment by myitcv** [comment]
@bcmills I don't think you can expect:

```
vgo get github.com/docker/docker/client@v17.05.0-ce
```

to work because `vgo get` works on modules, not packages. Related: https://github.com/golang/go/issues/24687#issuecomment-378997178 and https://github.com/golang/go/issues/25618#issuecomment-393789008

Back to the subject of the golang-nuts thread however, I do see a number of issues when I try to `vgo get` the moby module. Indeed I haven't yet managed to get this to complete (could well therefore be related to rate-limiting given the number of requests being made, even though my requests are fully authenticated):

<details>
<summary>Details</summary>
<pre><code>$ vgo get github.com/moby/moby@v17.03.2-ce
vgo: finding github.com/moby/moby v0.0.0-20170601211448-f5ec1e2936dc
vgo: stat github.com/go-check/check@4ed411733c5785b40214c70bce814c3a3a689609: cannot find hash 4ed411733c5785b40214c70bce814c3a3a689609
vgo: stat golang.org/x/net@2beffdc2e92c8a3027590f898fe88f69af48a3f8: git fetch --depth=1 origin 2beffdc2e92c8a3027590f898fe88f69af48a3f8 in /tmp/tmp.KOaGwuO91b/src/v/cache/vcswork/4a22365141bc4eea5d5ac4a1395e653f2669485db75ef119e7bbec8e19b12a21: exit status 128:
	fatal: expected shallow/unshallow, got ERR internal server error
	fatal: The remote end hung up unexpectedly
vgo: stat github.com/docker/go@v1.5.1-1-1-gbaf439e: unknown revision "v1.5.1-1-1-gbaf439e"
vgo: stat github.com/opencontainers/runc@54296cf40ad8143b62dbcaa1d90e520a2136ddfe: cannot find hash 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
vgo: stat bitbucket.org/ww/goautoneg@75cd24fc2f2c2a2088577d12123ddee5f54e0675: git fetch --depth=1 origin 75cd24fc2f2c2a2088577d12123ddee5f54e0675 in /tmp/tmp.KOaGwuO91b/src/v/cache/vcswork/52eb1c0593bdece4d4ec1f51b6d400c08ce21540252af4c262ec3a940587d7ee: exit status 128:
	remote: Not Found
	fatal: unable to access 'https://bitbucket.org/ww/goautoneg/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
vgo: stat github.com/spf13/cobra@v1.5: unknown revision "v1.5"
vgo: finding github.com/Azure/go-ansiterm v0.0.0-20160425224613-388960b65524
vgo: finding github.com/deckarep/golang-set v0.0.0-20141123011944-ef32fa3046d9
vgo: finding github.com/prometheus/client_model v0.0.0-20150212101744-fa8ad6fec335
vgo: finding github.com/gorilla/context v0.0.0-20160226214623-1ea25387ff6f
vgo: finding github.com/docker/swarmkit v0.0.0-20170516190019-2591ac368b6a
vgo: finding github.com/coreos/etcd v0.0.0-20160826165359-3a49cbb769eb
vgo: finding github.com/inconshreveable/mousetrap v0.0.0-20141017200713-76626ae9c91c
vgo: finding github.com/prometheus/client_golang v0.0.0-20160802072246-52437c81da6b
vgo: finding github.com/docker/libkv v0.0.0-20161109010621-1d8431073ae0
vgo: finding github.com/Microsoft/hcsshim v0.5.12
vgo: stat bitbucket.org/ww/goautoneg@75cd24fc2f2c2a2088577d12123ddee5f54e0675: git fetch --depth=1 origin 75cd24fc2f2c2a2088577d12123ddee5f54e0675 in /tmp/tmp.KOaGwuO91b/src/v/cache/vcswork/52eb1c0593bdece4d4ec1f51b6d400c08ce21540252af4c262ec3a940587d7ee: exit status 128:
	remote: Not Found
	fatal: unable to access 'https://bitbucket.org/ww/goautoneg/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
vgo: finding github.com/xeipuuv/gojsonpointer v0.0.0-20151027082146-e0fe6f683076
vgo: finding github.com/docker/libnetwork v0.0.0-20170518152629-57248dc8d53e
vgo: finding github.com/go-ini/ini v0.0.0-20151105010020-060d7da055ba
vgo: finding github.com/fluent/fluent-logger-golang v1.2.1
vgo: finding github.com/ugorji/go v0.0.0-20151028022000-f1f1a805ed36
vgo: finding github.com/docker/containerd v0.0.0-20170315145545-4ab9917febca
vgo: finding github.com/vishvananda/netns v0.0.0-20150710222425-604eaf189ee8
vgo: finding github.com/armon/go-radix v0.0.0-20150105235045-e39d623f12e8
vgo: finding github.com/seccomp/libseccomp-golang v0.0.0-20160531183505-32f571b70023
vgo: finding github.com/pivotal-golang/clock v0.0.0-20151018222946-3fd3c1944c59
vgo: finding github.com/coreos/pkg v0.0.0-20160620232715-fa29b1d70f0b
vgo: finding google.golang.org/cloud v0.0.0-20151218002640-dae7e3d993bc
vgo: finding github.com/samuel/go-zookeeper v0.0.0-20150415181332-d0e0d8e11f31
vgo: finding github.com/docker/go-units v0.0.0-20161020213227-8a7beacffa30
vgo: finding github.com/flynn-archive/go-shlex v0.0.0-20150515145356-3f9db97f8568
vgo: finding github.com/bsphere/le_go v0.0.0-20160908175455-d3308aafe090
vgo: finding github.com/golang/mock v0.0.0-20160127222235-bd3c8e81be01
vgo: finding github.com/docker/notary v0.4.2
vgo: finding github.com/Microsoft/go-winio v0.3.8
vgo: finding github.com/opencontainers/runtime-spec v0.0.0-20160926201932-1c7c27d043c2
vgo: finding github.com/gorilla/mux v0.0.0-20160317213430-0eeaf8392f5b
vgo: finding github.com/vdemeester/shakers v0.0.0-20160210082636-24d7f1d6a71a
vgo: finding github.com/godbus/dbus v0.0.0-20160408155243-5f6efc7ef275
vgo: finding github.com/docker/docker-credential-helpers v0.0.0-20160906164316-f72c04f1d8e7
vgo: finding google.golang.org/grpc v1.0.2
vgo: finding golang.org/x/oauth2 v0.0.0-20151204193638-2baa8a1b9338
vgo: finding github.com/google/certificate-transparency v0.0.0-20161025093837-d90e65c3a079
vgo: finding github.com/mattn/go-shellwords v1.0.0
vgo: finding github.com/hashicorp/golang-lru v0.0.0-20160207214719-a0d98a5f2880
vgo: finding github.com/Sirupsen/logrus v0.11.0
vgo: finding github.com/imdario/mergo v0.0.0-20151231081848-bc0f15622cd2
vgo: finding github.com/docker/go-connections v0.0.0-20170204000113-ecb4cb2dd420
vgo: finding github.com/hashicorp/go-memdb v0.0.0-20160226183831-608dda3b1410
vgo: finding google.golang.org/api v0.0.0-20151217002415-dc6d2353af16
vgo: finding github.com/xeipuuv/gojsonschema v0.0.0-20160323030313-93e72a773fad
vgo: finding github.com/mattn/go-sqlite3 v1.1.0
vgo: finding github.com/BurntSushi/toml v0.0.0-20150127021243-f706d00e3de6
vgo: finding github.com/hashicorp/serf v0.0.0-20160317193612-598c54895cc5
vgo: finding github.com/beorn7/perks v0.0.0-20160804104726-4c0e84591b9a
vgo: finding github.com/mistifyio/go-zfs v0.0.0-20160425201758-22c9b32c84eb
vgo: finding github.com/kr/pty v0.0.0-20150511174710-5cf931ef8f76
vgo: finding github.com/docker/go-metrics v0.0.0-20160815190133-86138d05f285
vgo: finding github.com/philhofer/fwd v0.0.0-20150401190312-899e4efba8ea
vgo: finding github.com/RackSec/srslog v0.0.0-20161121191927-456df3a81436
vgo: finding golang.org/x/crypto v0.0.0-20160408163010-3fbbcd23f1cb
vgo: finding github.com/prometheus/common v0.0.0-20160801171955-ebdfc6da4652
vgo: finding github.com/tinylib/msgp v0.0.0-20150407130441-75ee40d2601e
vgo: finding github.com/Graylog2/go-gelf v0.0.0-20160209094338-aab2f594e458
vgo: finding github.com/tonistiigi/fifo v0.0.0-20161107232433-140564397569
vgo: finding github.com/xeipuuv/gojsonreference v0.0.0-20150808065054-e02fc20de94c
vgo: finding golang.org/x/sys v0.0.0-20160916181909-8f0908ab3b24
vgo: finding github.com/armon/go-metrics v0.0.0-20150106224455-eb0af217e5e9
vgo: finding github.com/davecgh/go-spew v0.0.0-20160907170601-6d212800a42e
vgo: finding github.com/aws/aws-sdk-go v1.4.22
vgo: finding github.com/spf13/pflag v0.0.0-20161018230844-dabebe21bf79
vgo: finding github.com/vbatts/tar-split v0.10.1
vgo: finding github.com/miekg/pkcs11 v0.0.0-20160222192025-df8ae6ca7304
vgo: finding github.com/hashicorp/go-immutable-radix v0.0.0-20160222071000-8e8ed81f8f0b
vgo: finding github.com/boltdb/bolt v0.0.0-20160913165339-fff57c100f4d
vgo: finding gopkg.in/yaml.v2 v2.0.0-20160301204022-a83829b6f129
vgo: finding github.com/mreiferson/go-httpclient v0.0.0-20151014142300-63fe23f74347
vgo: finding github.com/pkg/errors v0.0.0-20161002052512-839d9e913e06
vgo: finding github.com/syndtr/gocapability v0.0.0-20150716010906-2c00daeb6c3b
vgo: finding github.com/docker/go-events v0.0.0-20160826205136-18b43f1bc85d
vgo: finding github.com/vishvananda/netlink v0.0.0-20161119221931-482f7a52b758
vgo: finding golang.org/x/time v0.0.0-20160202183820-a4bde1265759
vgo: finding github.com/coreos/go-systemd v0.0.0-20151104194251-b4a58d95188d
vgo: finding github.com/hashicorp/go-msgpack v0.0.0-20140221154404-71c2886f5a67
vgo: finding github.com/matttproud/golang_protobuf_extensions v0.0.0-20150406173934-fc2b8d3a73c4
vgo: finding github.com/mitchellh/mapstructure v0.0.0-20161020161836-f3009df150da
vgo: finding github.com/prometheus/procfs v0.0.0-20160411190841-abf152e5f3e9
vgo: finding github.com/cloudflare/cfssl v0.0.0-20160825002822-7fb22c8cba7e
vgo: finding github.com/pborman/uuid v0.0.0-20160209185913-a97ce2ca70fa
vgo: finding github.com/fsnotify/fsnotify v1.2.11
vgo: finding github.com/miekg/dns v0.0.0-20151202105714-75e6e86cc601
vgo: finding github.com/hashicorp/go-multierror v0.0.0-20150127051936-fcdddc395df1
vgo: finding github.com/hashicorp/consul v0.5.2
vgo: finding github.com/gogo/protobuf v0.0.0-20160824171236-909568be09de
vgo: finding github.com/docker/distribution v0.0.0-20161216195125-28602af35ace
vgo: finding github.com/tchap/go-patricia v0.0.0-20160811102535-666120de432a
vgo: finding github.com/jmespath/go-jmespath v0.0.0-20160202185014-0b12d6b521d8
vgo: finding github.com/golang/protobuf v0.0.0-20160829194233-1f49d83d9aa0
vgo: finding github.com/docker/libtrust v0.0.0-20150526203908-9cbd2a1374f4
vgo: finding github.com/hashicorp/memberlist v0.0.0-20160329060508-88ac4de0d1a0
vgo: finding github.com/agl/ed25519 v0.0.0-20140907235247-d2b94fd789ea
vgo: finding github.com/mitchellh/mapstructure v0.0.0-20160212031839-d2dd02622084
vgo: finding github.com/mattn/go-isatty v0.0.0-20151211000621-56b76bdf51f7
vgo: finding github.com/armon/go-radix v0.0.0-20160115234725-4239b77079c7
vgo: finding github.com/hashicorp/memberlist v0.0.0-20160307183129-cef12ad58224
vgo: finding github.com/armon/go-metrics v0.0.0-20160307061154-f303b03b91d7
vgo: finding github.com/hashicorp/go.net v0.0.0-20151006203346-104dcad90073
vgo: finding github.com/ryanuber/columnize v0.0.0-20150915232942-983d3a5fab1b
vgo: finding golang.org/x/sys v0.0.0-20160303154559-7a56174f0086
vgo: finding github.com/miekg/dns v0.0.0-20160308070806-b9171237b064
vgo: finding github.com/hashicorp/mdns v0.0.0-20151206042412-9d85cf22f9f8
vgo: finding github.com/mitchellh/cli v0.0.0-20160204055545-5c87c51cedf7
vgo: finding github.com/hashicorp/go-msgpack v0.0.0-20150518234257-fa3f63826f7c
vgo: finding github.com/hashicorp/logutils v0.0.0-20150609070431-0dc08b1671f3
vgo: finding github.com/hashicorp/go-syslog v0.0.0-20150218181946-42a2b573b664
vgo: finding github.com/bgentry/speakeasy v0.0.0-20150902231413-36e9cfdd6909
vgo: finding github.com/armon/circbuf v0.0.0-20150827004946-bbbad097214e
vgo: finding github.com/daaku/go.zipexe v0.0.0-20150329023125-a5fe2436ffcb
vgo: finding github.com/akavel/rsrc v0.0.0-20151103204339-ba14da1f8271
vgo: finding github.com/jmoiron/sqlx v0.0.0-20160206221533-398dd5876282
vgo: finding github.com/stretchr/objx v0.0.0-20150928122152-1a9d0bb9f541
vgo: finding github.com/GeertJohan/go.rice v0.0.0-20160123214158-0f3f5fde32fd
vgo: finding github.com/kardianos/osext v0.0.0-20151222153229-29ae4ffbc9a6
vgo: finding golang.org/x/net v0.0.0-20160609051231-3f122ce3dbbe
vgo: finding github.com/rcrowley/go-metrics v0.0.0-20160113235030-51425a2415d2
vgo: finding github.com/mattn/go-sqlite3 v0.0.0-20160201053437-c5aee9649735
vgo: finding github.com/GeertJohan/go.incremental v0.0.0-20140220125304-92fd0ce4a694
vgo: finding github.com/cloudflare/cfssl_trust v0.0.0-20160211195630-555f7ac5ef2b
vgo: finding github.com/davecgh/go-spew v0.0.0-20151105211317-5215b55f46b2
vgo: finding github.com/pmezard/go-difflib v0.0.0-20160110105554-792786c7400a
vgo: finding github.com/lib/pq v0.0.0-20160209143749-69552e54d2a9
vgo: finding github.com/go-sql-driver/mysql v0.0.0-20140603195003-a732e14c62dd
vgo: finding github.com/jessevdk/go-flags v0.0.0-20160207074515-97448c91aac7
vgo: finding github.com/stathat/go v0.0.0-20160126222115-cf69b0bcb804
vgo: finding golang.org/x/crypto v0.0.0-20160126184038-1f22c0103821
vgo: finding github.com/kisielk/sqlstruct v0.0.0-20150923205031-648daed35d49
vgo: finding github.com/mitchellh/iochan v0.0.0-20150529224432-87b45ffd0e95
vgo: finding github.com/google/certificate-transparency v0.0.0-20160709091406-0f6e3d1d1ba4
vgo: finding github.com/jmhodges/clock v0.0.0-20151001212940-3c4ebd218625
vgo: finding github.com/cloudflare/go-metrics v0.0.0-20151117154305-6a9aea36fb41
vgo: finding github.com/stretchr/testify v0.0.0-20160129193106-9f9027faeb0d
vgo: finding github.com/kisom/goutils v0.0.0-20160428212144-fb87692b5525
vgo: finding github.com/cloudflare/redoctober v0.0.0-20160202033125-18b5ac859f0a
vgo: finding github.com/mitchellh/gox v0.0.0-20151230230934-39862d88e853
vgo: finding github.com/stretchr/objx v0.0.0-20140526180921-cbeaeb16a013
vgo: finding github.com/davecgh/go-spew v0.0.0-20150619202934-2df174808ee0
vgo: finding github.com/pmezard/go-difflib v0.0.0-20151028094244-d8ed2627bdf0
vgo: finding github.com/golang/groupcache v0.0.0-20160516000752-02826c3e7903
vgo: finding github.com/kballard/go-shellquote v0.0.0-20150810074751-d8ec1a69a250
vgo: finding github.com/olekukonko/tablewriter v0.0.0-20160115111002-cca8bbc07984
vgo: finding github.com/urfave/cli v0.0.0-20160620154522-6011f165dc28
vgo: finding github.com/beorn7/perks v0.0.0-20150223135152-b965b613227f
vgo: finding github.com/kr/pty v0.0.0-20151007230424-f7ee69f31298
vgo: finding github.com/golang/protobuf v0.0.0-20160608215545-8616e8ee5e20
vgo: finding github.com/prometheus/procfs v0.0.0-20150928173926-454a56f35412
vgo: finding github.com/shurcooL/sanitized_anchor_name v0.0.0-20151028001915-10ef21a441db
vgo: finding github.com/cockroachdb/cmux v0.0.0-20160228191917-112f0506e774
vgo: finding github.com/mattn/go-runewidth v0.0.0-20160315040712-d6bea18f7897
vgo: finding github.com/spf13/cobra v0.0.0-20151124153217-1c44ec8d3f15
vgo: finding github.com/coreos/go-semver v0.0.0-20150304020126-568e959cd898
vgo: finding github.com/cpuguy83/go-md2man v0.0.0-20150803153522-71acacd42f85
vgo: finding gopkg.in/yaml.v2 v2.0.0-20150924142314-53feefa2559f
vgo: finding github.com/prometheus/client_golang v0.0.0-20151008143247-e51041b3fa41
vgo: finding github.com/jonboulle/clockwork v0.0.0-20160615175015-2eee05ed7941
vgo: finding github.com/spf13/pflag v0.0.0-20151013200643-08b1a584251b
vgo: finding github.com/grpc-ecosystem/grpc-gateway v0.0.0-20160715013742-f52d055dc48a
vgo: finding github.com/xiang90/probing v0.0.0-20160813154853-07dd2e8dfe18
vgo: finding golang.org/x/net v0.0.0-20160225202940-6acef71eb696
vgo: finding github.com/dustin/go-humanize v0.0.0-20151125214831-8929fe90cee4
vgo: finding github.com/akrennmair/gopcap v0.0.0-20150728160502-00e11033259a
vgo: finding golang.org/x/crypto v0.0.0-20150218234220-1351f936d976
vgo: finding gopkg.in/cheggaaa/pb.v1 v1.0.0-20160321211028-29ad9b62f9e0
vgo: finding github.com/google/btree v0.0.0-20160524151835-7d79101e329e
vgo: finding github.com/stretchr/testify v0.0.0-20140128171827-9cc77fa25329
vgo: finding golang.org/x/sys v0.0.0-20150901164945-9c60d1c508f5
vgo: finding github.com/coreos/go-systemd v0.0.0-20160815185329-bfdc81d0d7e0
vgo: finding github.com/russross/blackfriday v0.0.0-20151117072312-300106c228d5
vgo: finding github.com/golang/glog v0.0.0-20141105023935-44145f04b68c
vgo: finding github.com/prometheus/common v0.0.0-20151014055050-ffe929a3f4c4
vgo: finding github.com/ghodss/yaml v0.0.0-20150909031657-73d445a93680
vgo: finding github.com/spacejam/loghisto v0.0.0-20150819220310-323309774dec
vgo: finding google.golang.org/grpc v0.0.0-20160819002236-231b4cfea0e7
vgo: finding github.com/boltdb/bolt v0.0.0-20160818170152-583e8937c61f
vgo: finding github.com/gogo/protobuf v0.0.0-20160718161353-e18d7aa8f8c6
vgo: stat rsc.io/letsencrypt@e770c10b0f1a64775ae91d240407ce00d1a5bdeb: cannot find hash e770c10b0f1a64775ae91d240407ce00d1a5bdeb
vgo: finding github.com/bugsnag/panicwrap v0.0.0-20151223152923-e2c28503fcd0
vgo: finding github.com/aws/aws-sdk-go v0.0.0-20160708000820-90dec2183a5f
vgo: finding github.com/gorilla/handlers v0.0.0-20150720190736-60c7bfde3e33
vgo: finding github.com/gorilla/context v0.0.0-20140604161150-14f550f51af5
vgo: finding github.com/Azure/azure-sdk-for-go v0.0.0-20161103201839-0b5fe2abe027
vgo: finding github.com/docker/libtrust v0.0.0-20150114040149-fa567046d9b1
vgo: finding gopkg.in/yaml.v2 v2.0.0-20150116202057-bef53efd0c76
vgo: finding github.com/jmespath/go-jmespath v0.0.0-20160803190731-bd40a432e4c7
vgo: finding github.com/spf13/pflag v0.0.0-20150601220040-564482062245
vgo: finding gopkg.in/square/go-jose.v1 v1.0.0-20160329203311-40d457b43924
vgo: finding github.com/golang/protobuf v0.0.0-20160321223353-8d92cf5fc15a
vgo: finding github.com/mitchellh/mapstructure v0.0.0-20150528213339-482a9fd5fa83
vgo: finding github.com/yvasiyarov/go-metrics v0.0.0-20140926110328-57bccd1ccd43
vgo: finding github.com/go-ini/ini v0.0.0-20161120031036-2ba15ac2dc9c
vgo: finding github.com/bugsnag/osext v0.0.0-20130617224835-0dd3f918b21b
vgo: finding golang.org/x/crypto v0.0.0-20150531185727-c10c31b5e94b
vgo: finding github.com/spf13/cobra v0.0.0-20150605180824-312092086bed
vgo: finding google.golang.org/cloud v0.0.0-20151119220103-975617b05ea8
vgo: finding github.com/docker/goamz v0.0.0-20160206023946-f0a21f5b2e12
vgo: finding github.com/miekg/dns v0.0.0-20161122061214-271c58e0c14f
vgo: finding github.com/ncw/swift v0.0.0-20160617132549-b964f2ca856a
vgo: finding github.com/denverdino/aliyungo v0.0.0-20161108032828-afedced274aa
vgo: finding github.com/bugsnag/bugsnag-go v0.0.0-20141110184014-b1d153021fcd
vgo: finding github.com/Sirupsen/logrus v0.0.0-20150409230825-55eb11d21d2a
vgo: finding github.com/xenolf/lego v0.0.0-20160613233155-a9d8cec0e656
vgo: finding github.com/yvasiyarov/gorelic v0.0.0-20141212073537-a9bba5b9ab50
vgo: finding github.com/garyburd/redigo v0.0.0-20150301180006-535138d7bcd7
vgo: finding golang.org/x/net v0.0.0-20160322021652-4876518f9e71
vgo: finding google.golang.org/api v0.0.0-20160322025152-9bf6e6e569ff
vgo: finding github.com/gorilla/mux v0.0.0-20140926153814-e444e69cbd2e
vgo: finding gopkg.in/check.v1 v1.0.0-20141024133853-64131543e789
vgo: finding google.golang.org/grpc v0.0.0-20160317175043-d3ddb4469d5a
vgo: finding github.com/stevvooe/resumable v0.0.0-20150521211217-51ad44105773
vgo: finding github.com/yvasiyarov/newrelic_platform_go v0.0.0-20140908184405-b21fdbd4370f
vgo: finding google.golang.org/appengine v0.0.0-20160301025000-12d5545dc1cf
vgo: finding golang.org/x/oauth2 v0.0.0-20160304213135-045497edb623
vgo: finding github.com/feyeleanor/slices v0.0.0-20130225013708-bb44bb2e4817
vgo: finding github.com/cbroglie/mapstructure v0.0.0-20150405232821-25325b46b67d
vgo: finding github.com/feyeleanor/raw v0.0.0-20130327193431-724aedf6e1a5
vgo: finding github.com/feyeleanor/sets v0.0.0-20130227004140-6c54cb57ea40
vgo: finding github.com/bitly/go-simplejson v0.0.0-20150915165335-aabad6e81978
vgo: finding gopkg.in/check.v1 v1.0.0-20160105164936-4f90aeace3a2
vgo: finding github.com/miekg/dns v0.0.0-20151102115150-d27455715200
vgo: finding github.com/boltdb/bolt v0.0.0-20160322034321-c6ba97b89e04
vgo: finding github.com/codegangsta/cli v0.0.0-20150909014853-a65b733b303f
vgo: finding github.com/docker/go-events v0.0.0-20160323060050-2e7d35281612
vgo: finding github.com/seccomp/libseccomp-golang v0.0.0-20150813023252-1b506fc7c24e
vgo: finding github.com/vishvananda/netlink v0.0.0-20161115190107-17ea11b5a11c
vgo: finding github.com/gorilla/mux v0.0.0-20150311031735-8096f4750345
vgo: finding github.com/opencontainers/runc v0.0.0-20151215222150-ba1568de3993
vgo: finding github.com/coreos/etcd v0.0.0-20150910170245-e4561dd8cfb1
vgo: finding github.com/gorilla/context v0.0.0-20141217160251-215affda49ad
vgo: finding github.com/hashicorp/go-multierror v0.0.0-20150107203116-2167c8ec4077
vgo: finding github.com/Microsoft/hcsshim v0.0.0-20161108200542-e439b7d2b63f
vgo: finding golang.org/x/sys v0.0.0-20160222202601-5eaf0df67e70
vgo: finding github.com/stretchr/testify v0.0.0-20150512124233-dab07ac62d49
vgo: stat bitbucket.org/ww/goautoneg@75cd24fc2f2c2a2088577d12123ddee5f54e0675: git fetch --depth=1 origin 75cd24fc2f2c2a2088577d12123ddee5f54e0675 in /tmp/tmp.KOaGwuO91b/src/v/cache/vcswork/52eb1c0593bdece4d4ec1f51b6d400c08ce21540252af4c262ec3a940587d7ee: exit status 128:
	remote: Not Found
	fatal: unable to access 'https://bitbucket.org/ww/goautoneg/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
vgo: finding github.com/gogo/protobuf v0.0.0-20160728085359-e33835a643a9
vgo: finding github.com/docker/go-units v0.0.0-20151222191443-8e2d4523730c
vgo: finding github.com/Sirupsen/logrus v0.0.0-20160317141110-4b6ea7319e21
vgo: finding github.com/mattn/go-shellwords v0.0.0-20160315040826-525bedee691b
vgo: finding golang.org/x/net v0.0.0-20150130075918-9dd48c277bcb
vgo: finding github.com/Microsoft/go-winio v0.0.0-20160621211438-ce2922f643c8
vgo: finding github.com/golang/protobuf v0.0.0-20150316215550-f7137ae6b19a
vgo: finding github.com/Azure/go-ansiterm v0.0.0-20160425224146-04b7f292a41f
vgo: finding github.com/ugorji/go v0.0.0-20150803141331-5abd4e96a45c
vgo: finding github.com/hashicorp/consul v0.0.0-20150202214222-954aec66231b
vgo: finding github.com/docker/docker v0.0.0-20161222213028-e4512d264741
vgo: finding github.com/docker/go-connections v0.0.0-20160212231911-34b5052da6b1
vgo: stat github.com/go-check/check@4ed411733c5785b40214c70bce814c3a3a689609: cannot find hash 4ed411733c5785b40214c70bce814c3a3a689609
vgo: stat golang.org/x/net@2beffdc2e92c8a3027590f898fe88f69af48a3f8: git fetch --depth=1 origin 2beffdc2e92c8a3027590f898fe88f69af48a3f8 in /tmp/tmp.KOaGwuO91b/src/v/cache/vcswork/4a22365141bc4eea5d5ac4a1395e653f2669485db75ef119e7bbec8e19b12a21: exit status 128:
	fatal: expected shallow/unshallow, got ERR internal server error
	fatal: The remote end hung up unexpectedly
vgo: stat github.com/docker/go@v1.5.1-1-1-gbaf439e: unknown revision "v1.5.1-1-1-gbaf439e"
vgo: finding github.com/docker/libkv v0.0.0-20160209183009-9fd56606e928
vgo: finding github.com/Microsoft/go-winio v0.0.0-20160306025729-f778f0501535
vgo: finding github.com/boltdb/bolt v0.0.0-20160906200929-e72f08ddb5a5
vgo: finding github.com/matttproud/golang_protobuf_extensions v1.0.0
vgo: finding github.com/stretchr/testify v1.1.4
vgo: finding github.com/docker/libnetwork v0.0.0-20161109232206-3ab699ea3657
vgo: finding github.com/opencontainers/runc v0.0.0-20160209185346-8e8d01d38d7b
vgo: finding github.com/docker/distribution v0.0.0-20160222205623-7230e9def796
vgo: finding github.com/vishvananda/netlink v0.0.0-20160629175746-e73bad418fd7
vgo: finding github.com/coreos/pkg v0.0.0-20160727233714-3ac0863d7acf
vgo: finding github.com/coreos/etcd v0.0.0-20160908070916-bd7107bd4bf2
vgo: finding github.com/nozzle/throttler v0.0.0-20150512200654-d9b45f19996c
vgo: finding golang.org/x/crypto v0.0.0-20161002164829-84e98f45760e
vgo: finding gopkg.in/godo.v2 v2.0.0-20160414202316-b5fd2f0bef1e
vgo: finding github.com/mattn/go-colorable v0.0.0-20160930084157-6c903ff4aa50
vgo: finding github.com/mgutz/to v0.0.0-20150801172905-2a0bcba06616
vgo: finding github.com/spf13/pflag v0.0.0-20151218134703-7f60f83a2c81
vgo: finding github.com/pkg/errors v0.0.0-20160613021747-01fa4104b9c2
vgo: finding github.com/coreos/go-systemd v0.0.0-20160826104600-43e4800a6165
vgo: finding github.com/mgutz/ansi v0.0.0-20150914162238-c286dcecd19f
vgo: finding github.com/docker/docker v0.0.0-20161007163301-febf53d91a43
vgo: finding github.com/mgutz/str v0.0.0-20150623153827-968bf66e3da8
vgo: finding github.com/docker/go-events v0.0.0-20160829185957-37d35add5005
vgo: finding golang.org/x/net v0.0.0-20160403195514-024ed629fd29
vgo: finding golang.org/x/sys v0.0.0-20161023150541-c200b10b5d5e
vgo: finding github.com/docker/go-units v0.0.0-20151215220059-954fed01cc61
vgo: finding github.com/spf13/cobra v0.0.0-20160117030938-8e91712f174c
vgo: lookup google.golang.org/api/storage/v1: module root is "google.golang.org/api"
vgo: finding github.com/howeyc/gopass v0.0.0-20161003130900-f5387c492211
vgo: finding github.com/phayes/permbits v0.0.0-20160117212716-f7e3ac5e859d
vgo: finding github.com/mgutz/minimist v0.0.0-20151219120022-39eb8cf573ca
vgo: finding github.com/docker/docker v0.0.0-20161202214020-0fb0d6700815
vgo: finding github.com/Sirupsen/logrus v0.0.0-20160928124828-f76d643702a3
vgo: finding github.com/mattn/go-isatty v0.0.0-20160806122752-66b8e73f3f5c
vgo: finding github.com/Azure/go-autorest v0.0.0-20161003183913-0781901f19f1
vgo: lookup google.golang.org/cloud/storage: module root is "google.golang.org/cloud"
vgo: lookup google.golang.org/cloud/compute/metadata: module root is "google.golang.org/cloud"
vgo: lookup google.golang.org/cloud/internal: module root is "google.golang.org/cloud"
vgo: finding github.com/google/btree v0.0.0-20150413163644-cc6329d4279e
vgo: stat bitbucket.org/ww/goautoneg@75cd24fc2f2c2a2088577d12123ddee5f54e0675: git fetch --depth=1 origin 75cd24fc2f2c2a2088577d12123ddee5f54e0675 in /tmp/tmp.KOaGwuO91b/src/v/cache/vcswork/52eb1c0593bdece4d4ec1f51b6d400c08ce21540252af4c262ec3a940587d7ee: exit status 128:
	remote: Not Found
	fatal: unable to access 'https://bitbucket.org/ww/goautoneg/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
vgo: finding github.com/xiang90/probing v0.0.0-20150806223128-6a0cc1ae81b4
vgo: finding golang.org/x/net v0.0.0-20150320034621-7dbad50ab5b3
vgo: finding github.com/boltdb/bolt v0.0.0-20150825012340-90fef389f980
vgo: finding github.com/golang/protobuf v0.0.0-20160221214941-3c84672111d9
vgo: finding github.com/MichaelTJones/walk v0.0.0-20140707193007-3af09438b0ab
vgo: finding golang.org/x/oauth2 v0.0.0-20150331072446-3046bc76d6df
vgo: finding github.com/bradfitz/http2 v0.0.0-20150329061506-3e36af6d3af0
vgo: finding github.com/prometheus/client_golang v0.0.0-20150530155902-a842dc11e062
vgo: stat bitbucket.org/ww/goautoneg@75cd24fc2f2c2a2088577d12123ddee5f54e0675: git fetch --depth=1 origin 75cd24fc2f2c2a2088577d12123ddee5f54e0675 in /tmp/tmp.KOaGwuO91b/src/v/cache/vcswork/52eb1c0593bdece4d4ec1f51b6d400c08ce21540252af4c262ec3a940587d7ee: exit status 128:
	remote: Not Found
	fatal: unable to access 'https://bitbucket.org/ww/goautoneg/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
vgo: finding github.com/jonboulle/clockwork v0.0.0-20141017032234-72f9bd7c4e0c
vgo: finding github.com/golang/protobuf v0.0.0-20150209043950-5677a0e3d5e8
vgo: finding github.com/coreos/pkg v0.0.0-20150813182229-42a8c3b1a6f9
vgo: finding github.com/prometheus/procfs v0.0.0-20150223001136-6c34ef819e19
vgo: finding github.com/gogo/protobuf v0.0.0-20150626120410-64f27bf06efe
vgo: finding github.com/prometheus/procfs v0.0.0-20150519200031-ee2372b58cee
vgo: finding google.golang.org/grpc v0.0.0-20150513182145-f5ebd86be717
vgo: finding github.com/coreos/go-systemd v0.0.0-20150630005322-cea488b4e685
vgo: finding github.com/golang/protobuf v0.0.0-20150220011730-c22ae3cf020a
vgo: finding github.com/codegangsta/cli v0.0.0-20140923033435-f7ebb761e83e
vgo: finding github.com/satori/uuid v0.0.0-20160927100844-b061729afc07
vgo: finding github.com/dgrijalva/jwt-go v0.0.0-20160831183534-24c63f56522a
vgo: finding github.com/rakyll/pb v0.0.0-20140116112036-dc507ad06b74
vgo: finding golang.org/x/text v0.0.0-20160922232553-a7c023693a94
vgo: finding golang.org/x/crypto v0.0.0-20160929090514-a20de3fa94e0
vgo: finding golang.org/x/net v0.0.0-20160929200032-8058fc7b18f8
vgo: finding github.com/Azure/azure-sdk-for-go v0.0.0-20150611225107-97d9593768bb
vgo: finding github.com/bradfitz/http2 v0.0.0-20150509182458-f8202bc903bd
vgo: finding github.com/denverdino/aliyungo v0.0.0-20151224125954-6ffb587da9da
vgo: finding github.com/aws/aws-sdk-go v0.0.0-20160202195807-49c3892b61af
vgo: finding github.com/noahdesu/go-ceph v0.0.0-20150504145059-b15639c44c05
vgo: finding golang.org/x/oauth2 v0.0.0-20150701215807-8914e5017ca2
vgo: finding github.com/go-ini/ini v0.0.0-20160106105616-afbd495e5aae
vgo: finding google.golang.org/grpc v0.0.0-20150624224246-91c8b79535eb
vgo: finding google.golang.org/cloud v0.0.0-20151020041914-2400193c85c3
vgo: finding github.com/ncw/swift v0.0.0-20151102203822-c54732e87b0b
vgo: finding google.golang.org/api v0.0.0-20150716160007-18450f4e95c7
vgo: finding golang.org/x/net v0.0.0-20151022140915-2cba614e8ff9
vgo: finding github.com/golang/protobuf v0.0.0-20150720060306-0f7a9caded1f
vgo: lookup google.golang.org/appengine/internal: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/appengine/internal/app_identity: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/appengine/internal/base: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/appengine/internal/datastore: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/appengine/internal/log: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/appengine/internal/modules: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/appengine/internal/remote_api: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/cloud/compute/metadata: module root is "google.golang.org/cloud"
vgo: lookup google.golang.org/cloud/internal: module root is "google.golang.org/cloud"
vgo: lookup google.golang.org/grpc/benchmark: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/benchmark/client: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/benchmark/grpc_testing: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/benchmark/server: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/benchmark/stats: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/codes: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/credentials: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/credentials/oauth: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/examples/helloworld/greeter_client: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/examples/helloworld/greeter_server: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/examples/helloworld/helloworld: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/examples/route_guide/client: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/examples/route_guide/routeguide: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/examples/route_guide/server: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/grpclog: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/grpclog/glogger: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/health: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/interop/client: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/interop/grpc_testing: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/interop/server: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/metadata: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/naming: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/test/codec_perf: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/test/grpc_testing: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/transport: module root is "google.golang.org/grpc"
vgo: lookup gopkg.in/dancannon/gorethink.v2/encoding: invalid module path "gopkg.in/dancannon/gorethink.v2/encoding"
vgo: lookup gopkg.in/dancannon/gorethink.v2/ql2: invalid module path "gopkg.in/dancannon/gorethink.v2/ql2"
vgo: lookup gopkg.in/dancannon/gorethink.v2/types: invalid module path "gopkg.in/dancannon/gorethink.v2/types"
vgo: lookup google.golang.org/grpc/internal: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/peer: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/health/grpc_health_v1: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/interop: module root is "google.golang.org/grpc"
vgo: finding github.com/Shopify/logrus-bugsnag v0.0.0-20160517173102-5a46080c635f
vgo: finding github.com/agtorre/gocolorize v0.0.0-20140921225620-f42b554bf7f0
vgo: finding github.com/go-sql-driver/mysql v0.0.0-20150503060823-0cc29e9fe8e2
vgo: finding github.com/denisenkom/go-mssqldb v0.0.0-20160121200924-6e7f3d73dade
vgo: finding github.com/cenkalti/backoff v0.0.0-20150814094333-4dc77674acea
vgo: finding gopkg.in/fatih/pool.v2 v2.0.0-20150325163252-cba550ebf9bc
vgo: finding github.com/miekg/pkcs11 v0.0.0-20160420085217-ba39b9c6300b
vgo: finding github.com/russross/blackfriday v0.0.0-20150720194836-8cec3a854e68
vgo: finding github.com/mattn/go-sqlite3 v0.0.0-20150629235728-b4142c444a89
vgo: finding github.com/prometheus/client_golang v0.0.0-20151026012706-449ccefff16c
vgo: finding golang.org/x/sys v0.0.0-20160113011410-442cd600860c
vgo: finding github.com/xordataexchange/crypt v0.0.0-20150523230031-749e360c8f23
vgo: finding github.com/stevvooe/resumable v0.0.0-20150825013942-eb352b28d119
vgo: finding github.com/matttproud/golang_protobuf_extensions v0.0.0-20151011102529-d0c3fe89de86
vgo: finding github.com/agl/ed25519 v0.0.0-20150830182803-278e1ec8e8a6
vgo: finding github.com/tobi/airbrake-go v0.0.0-20151005181455-a3cdd910a3ff
vgo: finding github.com/jinzhu/gorm v0.0.0-20150721070657-82d726bbfd8c
vgo: finding github.com/magiconair/properties v0.0.0-20150601221201-624009598839
vgo: finding github.com/coreos/go-etcd v0.0.0-20151026160318-003851be7bb0
vgo: finding github.com/juju/loggo v0.0.0-20150527035839-8477fc936adf
vgo: finding github.com/erikstmartin/go-testdb v0.0.0-20160219214506-8d10e4a1bae5
vgo: finding github.com/spf13/viper v0.0.0-20150530192845-be5ff3e4840c
vgo: finding github.com/docker/docker v0.0.0-20160809144754-91853e44aeb2
vgo: finding gopkg.in/fsnotify.v1 v1.0.0-20160303034835-875cf421b32f
vgo: finding github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
vgo: finding github.com/docker/go v0.0.0-20160303222718-d30aec9fd63c
vgo: finding github.com/stvp/go-udp-testing v0.0.0-20160310180724-06eb4f886d9f
vgo: finding github.com/docker/go-connections v0.0.0-20160304224811-f549a9393d05
vgo: finding github.com/getsentry/raven-go v0.0.0-20160113000659-1cc47a9463b9
vgo: finding github.com/armon/consul-api v0.0.0-20150107205647-dcfedd50ed53
vgo: finding github.com/jinzhu/now v0.0.0-20151001141511-ce80572eb55a
vgo: finding github.com/Sirupsen/logrus v0.0.0-20160524132453-6d9ae300aaf8
vgo: finding github.com/BurntSushi/toml v0.0.0-20140627204940-bd2bdf7f18f8
vgo: finding github.com/bugsnag/bugsnag-go v0.0.0-20150529004307-13fd6b8acda0
vgo: finding github.com/mitchellh/go-homedir v0.0.0-20150831190304-df55a15e5ce6
vgo: finding github.com/mitchellh/mapstructure v0.0.0-20150613213606-2caf8efc9366
vgo: finding github.com/dvsekhvalnov/jose2go v0.0.0-20150816204322-6387d3c1f5ab
vgo: finding github.com/robfig/pathtree v0.0.0-20140121041023-41257a1839e9
vgo: finding github.com/lib/pq v0.0.0-20150723085316-0dad96c0b94f
vgo: finding github.com/spf13/cast v0.0.0-20150508191742-4d07383ffe94
vgo: finding github.com/spf13/cobra v0.0.0-20160517171929-f36824430130
vgo: finding github.com/robfig/config v0.0.0-20141207224736-0f78529c8c7e
vgo: finding github.com/docker/go-units v0.0.0-20151230175859-0bbddae09c5a
vgo: finding github.com/spf13/jwalterweatherman v0.0.0-20141219030609-3d60171a6431
vgo: finding google.golang.org/appengine v0.0.0-20160322225941-41265fb44dec
vgo: finding github.com/google/gofuzz v0.0.0-20150304233714-bbcb9da2d746
vgo: finding github.com/stretchr/testify v0.0.0-20150620232711-089c7181b8c7
vgo: finding github.com/hailocab/go-hostpool v0.0.0-20160125115350-e80d13ce29ed
vgo: finding github.com/prometheus/common v0.0.0-20151026110434-4fdc91a58c9d
vgo: finding github.com/kr/pretty v0.0.0-20130510082846-bc9499caa0f4
vgo: finding github.com/spf13/pflag v0.0.0-20160427162146-cb88ea77998c
vgo: finding golang.org/x/net v0.0.0-20160726221601-6a513affb38d
vgo: finding github.com/docker/distribution v0.0.0-20160826182037-12acdf0a6c1e
vgo: finding github.com/prometheus/procfs v0.0.0-20151026012247-b1afdc266f54
vgo: finding gopkg.in/dancannon/gorethink.v2 v2.0.0-20160418200057-3742792da4bc
vgo: finding google.golang.org/grpc v0.0.0-20160730185010-452f01f3ae15
vgo: finding github.com/revel/revel v0.0.0-20150912071025-a9a2ff45fae4
vgo: finding github.com/kr/text v0.0.0-20130911015532-6807e777504f
vgo: finding github.com/ugorji/go v0.0.0-20160314172118-c062049c1793
vgo: finding github.com/coreos/etcd v0.0.0-20160526165313-6acb3d67fbe1
vgo: lookup google.golang.org/api/gensupport: module root is "google.golang.org/api"
vgo: finding github.com/golang/protobuf v0.0.0-20160727172617-c3cefd437628
vgo: finding github.com/shurcooL/sanitized_anchor_name v0.0.0-20150822220530-244f5ac324cb
vgo: finding golang.org/x/crypto v0.0.0-20160518162255-5bcd134fee4d
vgo: finding golang.org/x/oauth2 v0.0.0-20160323034610-93758b5cba8c
vgo: lookup google.golang.org/api/googleapi: module root is "google.golang.org/api"
vgo: lookup google.golang.org/api/googleapi/internal/uritemplates: module root is "google.golang.org/api"
vgo: lookup google.golang.org/api/storage/v1: module root is "google.golang.org/api"
vgo: lookup google.golang.org/appengine/internal: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/appengine/internal/app_identity: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/appengine/internal/base: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/appengine/internal/datastore: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/appengine/internal/log: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/appengine/internal/modules: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/appengine/internal/remote_api: module root is "google.golang.org/appengine"
vgo: lookup google.golang.org/cloud/compute/metadata: module root is "google.golang.org/cloud"
vgo: lookup google.golang.org/cloud/internal: module root is "google.golang.org/cloud"
vgo: lookup google.golang.org/cloud/internal/opts: module root is "google.golang.org/cloud"
vgo: lookup google.golang.org/cloud/storage: module root is "google.golang.org/cloud"
vgo: lookup google.golang.org/grpc/codes: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/credentials: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/grpclog: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/internal: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/metadata: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/naming: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/peer: module root is "google.golang.org/grpc"
vgo: lookup google.golang.org/grpc/transport: module root is "google.golang.org/grpc"
vgo: finding rsc.io/letsencrypt v0.0.0-20160420184355-a019c9e6fce0
vgo: finding github.com/ncw/swift v0.0.0-20160519162137-ce444d6d47c5
vgo: finding github.com/Azure/azure-sdk-for-go v0.0.0-20160210183655-95361a2573b1
vgo: lookup gopkg.in/square/go-jose.v1/cipher: invalid module path "gopkg.in/square/go-jose.v1/cipher"
vgo: lookup gopkg.in/square/go-jose.v1/json: invalid module path "gopkg.in/square/go-jose.v1/json"
vgo: finding github.com/xenolf/lego v0.0.0-20160328162834-ca19a90028e2
vgo: finding github.com/dgrijalva/jwt-go v0.0.0-20151230180000-afef698c326b
vgo: finding github.com/Azure/go-autorest v0.0.0-20160129200509-8ced4882956d
vgo: finding golang.org/x/crypto v0.0.0-20160113191126-3760e0168503
...
</code></pre>
</details>

<p/>

* `vgo: stat github.com/go-check/check@4ed411733c5785b40214c70bce814c3a3a689609: cannot find hash 4ed411733c5785b40214c70bce814c3a3a689609` - unclear what gives rise to this. There is also a similar error for `rsc.io`
* `vgo: stat golang.org/x/net@2beffdc2e92c8a3027590f898fe88f69af48a3f8` which ultimately results in `expected shallow/unshallow, got ERR internal server error` - this feels like we're missing a special parameter for golang.org git requests?
* `vgo: stat bitbucket.org/ww/goautoneg@75cd24fc2f2c2a2088577d12123ddee5f54e0675` - not sure what state the bitbucket VCS fetcher is in?

Incidentally, `vgo get -x ...` fails (which might have given us a bit more detail here): I've raised https://github.com/golang/go/issues/25918 for that.

**/cc** @kardianos

**Comment by klingtnet** [comment]
Can confirm this:

```
vgo get github.com/moby/moby@v17.03.2-ce   
vgo: finding github.com/moby/moby v0.0.0-20170601211448-f5ec1e2936dc
vgo: stat github.com/go-check/check@4ed411733c5785b40214c70bce814c3a3a689609: cannot find hash 4ed411733c5785b40214c70bce814c3a3a689609
vgo: stat golang.org/x/net@2beffdc2e92c8a3027590f898fe88f69af48a3f8: git fetch --depth=1 https://go.googlesource.com/net 2beffdc2e92c8a3027590f898fe88f69af48a3f8 in /home/alinz/.go/src/v/cache/vcswork/4a22365141bc4eea5d5ac4a1395e653f2669485db75ef119e7bbec8e19b12a21: exit status 128:
	fatal: expected shallow/unshallow, got ERR internal server error
	fatal: The remote end hung up unexpectedly
vgo: stat github.com/docker/go@v1.5.1-1-1-gbaf439e: unknown revision "v1.5.1-1-1-gbaf439e"
vgo: stat github.com/opencontainers/runc@54296cf40ad8143b62dbcaa1d90e520a2136ddfe: cannot find hash 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
vgo: stat bitbucket.org/ww/goautoneg@75cd24fc2f2c2a2088577d12123ddee5f54e0675: git fetch --depth=1 origin 75cd24fc2f2c2a2088577d12123ddee5f54e0675 in /home/alinz/.go/src/v/cache/vcswork/52eb1c0593bdece4d4ec1f51b6d400c08ce21540252af4c262ec3a940587d7ee: exit status 128:
	remote: Not Found
	fatal: repository 'https://bitbucket.org/ww/goautoneg/' not found
vgo: stat github.com/spf13/cobra@v1.5: unknown revision "v1.5"
...
vgo: stat bitbucket.org/ww/goautoneg@75cd24fc2f2c2a2088577d12123ddee5f54e0675: git fetch --depth=1 origin 75cd24fc2f2c2a2088577d12123ddee5f54e0675 in /home/alinz/.go/src/v/cache/vcswork/52eb1c0593bdece4d4ec1f51b6d400c08ce21540252af4c262ec3a940587d7ee: exit status 128:
	remote: Not Found
	fatal: repository 'https://bitbucket.org/ww/goautoneg/' not found
...
vgo: stat rsc.io/letsencrypt@e770c10b0f1a64775ae91d240407ce00d1a5bdeb: cannot find hash e770c10b0f1a64775ae91d240407ce00d1a5bdeb
...
vgo: stat bitbucket.org/ww/goautoneg@75cd24fc2f2c2a2088577d12123ddee5f54e0675: git fetch --depth=1 origin 75cd24fc2f2c2a2088577d12123ddee5f54e0675 in /home/alinz/.go/src/v/cache/vcswork/52eb1c0593bdece4d4ec1f51b6d400c08ce21540252af4c262ec3a940587d7ee: exit status 128:
	remote: Not Found
	fatal: repository 'https://bitbucket.org/ww/goautoneg/' not found
...
vgo: stat github.com/go-check/check@4ed411733c5785b40214c70bce814c3a3a689609: cannot find hash 4ed411733c5785b40214c70bce814c3a3a689609
vgo: stat golang.org/x/net@2beffdc2e92c8a3027590f898fe88f69af48a3f8: git fetch --depth=1 https://go.googlesource.com/net 2beffdc2e92c8a3027590f898fe88f69af48a3f8 in /home/alinz/.go/src/v/cache/vcswork/4a22365141bc4eea5d5ac4a1395e653f2669485db75ef119e7bbec8e19b12a21: exit status 128:
	fatal: expected shallow/unshallow, got ERR internal server error
	fatal: The remote end hung up unexpectedly
vgo: stat github.com/docker/go@v1.5.1-1-1-gbaf439e: unknown revision "v1.5.1-1-1-gbaf439e"
...
vgo: stat bitbucket.org/ww/goautoneg@75cd24fc2f2c2a2088577d12123ddee5f54e0675: git fetch --depth=1 origin 75cd24fc2f2c2a2088577d12123ddee5f54e0675 in /home/alinz/.go/src/v/cache/vcswork/52eb1c0593bdece4d4ec1f51b6d400c08ce21540252af4c262ec3a940587d7ee: exit status 128:
	remote: Not Found
	fatal: repository 'https://bitbucket.org/ww/goautoneg/' not found
...
```
Suprisingly, all of the errors refer to _existing_ revisions.

**Comment by rsc** [comment]
`vgo get github.com/docker/docker/client@v17.05.0-ce` works fine for me now. This report predates the modfetch.Lookup, modfetch.Import, etc fix, so I'm pretty sure that was it.

**Comment by pwaller** [comment]
@rsc I'm a little confused. The command as you spoke it in the comment above doesn't "work" for me (on the tip of master branch of vgo at time of writing golang/vgo@8a71b2bd9c54c265c37322f928113c849582486b):

```
$ vgo get github.com/docker/docker/client@v17.05.0-ce
vgo: finding github.com/docker/docker/client v17.05.0-ce
vgo: github.com/docker/docker/client v0.0.0-20170504205632-89658bed64c2: missing go.mod
vgo get: missing go.mod
```

Additionally, I can't figure out how to get https://github.com/pwaller/vgo-use-dockerclient to use docker `v17.x`. If I update the import in that repository to import `github.com/docker/docker/v17/client`, I get the following outcome:

```
$ vgo install
vgo: import "github.com/pwaller/vgo-use-dockerclient" ->
	import "github.com/docker/docker/v17/client" [/Users/pwaller/go/src/mod/github.com/docker/docker@v0.0.0-20170504205632-89658bed64c2/v17/client]: open /Users/pwaller/go/src/mod/github.com/docker/docker@v0.0.0-20170504205632-89658bed64c2/v17/client: no such file or directory
```

So I can't tell that this issue is fixed as it is stated by the reporter? This still seems to be blocking me from using any docker import post v1.x as far as I can tell, assuming that I have not misunderstood what I need to do to make that work.

This latter error also looks strange, and I can't easily tell what has gone wrong. Why is it looking for a v17 directory inside the repository?

/cc @bcmills

**Comment by bcmills** [comment]
It looks like `vgo get module@version` works, but `vgo get module/pkg@version` still does not (both at head and as of [CL 122480](https://golang.org/cl/122480)).

```
$ cd $(mktemp -d)

/tmp/tmp.mHqDxK72RJ$ export GOPATH=$(mktemp -d)

/tmp/tmp.mHqDxK72RJ$ cat > go.mod
module github.com/bcmills/importdocker

/tmp/tmp.mHqDxK72RJ$ vgo get github.com/docker/docker/client@v17.05.0-ce
vgo: finding github.com/docker/docker/client v17.05.0-ce
vgo: github.com/docker/docker/client v0.0.0-20170504205632-89658bed64c2: missing go.mod
vgo get: missing go.mod

/tmp/tmp.mHqDxK72RJ$ vgo get github.com/docker/docker@v17.05.0-ce
vgo: finding github.com/docker/docker v17.05.0-ce
vgo: downloading github.com/docker/docker v0.0.0-20170504205632-89658bed64c2
```

**Comment by bcmills** [comment]
> Why is it looking for a v17 directory inside the repository?

None of the `v17.x.x` commits have a `go.mod` file, and per https://research.swtch.com/vgo-module, “`vgo` will not use any v2 or later tag in a source code repository without first checking that it has a `go.mod` with a module path declaration ending in that major version (for example, `module "my/thing/v2"`). `Vgo` uses that declaration as evidence that the author is using semantic import versioning to name packages within that module.”

**Comment by pwaller** [comment]
Does that mean it is not possible to use v17 without docker introducing a `go.mod` file?

To answer my own question, presumably the way to do it is to depend on a `v0.0.0-date-sha` "pseudo-version" which happens to point at v17? If that is the solution, can I get vgo to synthesise that tag for me?

**Comment by bcmills** [comment]
Still not working at head, but the symptom has changed to `missing module for import`:

```
$ go version
go version devel +3fcfb1f573 Mon Jul 16 15:32:40 2018 +0000 linux/amd64

$ go mod -init -module 'github.com/bcmills/foo'
go: creating new go.mod: module github.com/bcmills/foo

$ go get github.com/docker/docker/client@v17.05.0-ce
go: finding github.com/docker/docker/client v17.05.0-ce
go: finding github.com/docker/docker/client latest
go: finding github.com/docker/docker v1.13.1
go: downloading github.com/docker/docker v1.13.1
go get github.com/docker/docker/client@v17.05.0-ce: missing module for import: github.com/docker/docker@v1.13.1 provides github.com/docker/docker/client
```

**Comment by rsc** [comment]
The problem here is that v17.05.0-ce is NOT a semantic version at all: the leading 0 in 05 makes it malformed.
(Also this is not the "ce" prerelease; they are using ce to denote the community edition.)
This is really a date-based version (May 2017) not a semantic version.

But because v1.13.1 was tagged earlier, it looks like docker depends on something that in turn depends back on docker and gets v1.13.1.

At the very least we need to diagnose this problem better in go get.

I changed the title because go get pkg@version does work in general.
