### ISSUE TITLE
go/doc: apply usual quote changes to package synopses

### ISSUE THREAD

**Issue by dotaheor** [golang/go#27759]
A typo of "foo bar"? Or other special reasons?

https://www.google.com/search?q=site%3Agolang.org+"``"
* https://golang.org/cmd/
* https://golang.org/pkg/
* ...

Might be related to: https://github.com/golang/go/issues/23389

**Comment by dsnet** [comment]
There's magical handling in the `go/doc` package to convert them into `“` and `”`.

https://github.com/golang/go/blob/620bd5a3bc640f60a00d8b49c27c51e8ce67e67b/src/go/doc/comment.go#L22-L43

**Comment by dotaheor** [comment]
but not. Bug?

**Comment by dsnet** [comment]
Ah, that wasn't clear to me. It seems to me that the `commentEscape` function is not being applied to the synopsis. However, I don't think it should either, since it assumes HTML is end-target output.

Personally, I'd rather see the special handling for the double back-ticks and double single-quote be removed. Go supports unicode, so the rare uses of them could just use the actual unicode characters for them.

**Comment by bcmills** [comment]
> Go supports unicode, so the rare uses of them could just use the actual unicode characters for them.

I'd be happy for us to stop [ab]using them in this way in standard library sources, but note that actually removing that support from `doc` would be a backward-incompatible change.

**Comment by bcmills** [comment]
CC @griesemer

**Comment by rsc** [comment]
No, we're not going to remove this handling. Existing docs exist.

**Comment by rsc** [comment]
Sorry, misunderstood - OK, then we should fix the synopses to do the same replacements. But let's not redefine the doc comment syntax and invalidate existing comments.

**Comment by dsnet** [comment]
I'm wary of this. The replacement logic is done by `doc.ToHTML` and converts the quotes to `&ldquo;` and `&rdquo;`. On the other hand `doc.ToText` does no replacement whatsoever. The `doc.Synopsis` function is used for both outputting to HTML and text. Auto-converting to the HTML entity is a bad for pure text outputs.

Now, if consistently convert the double single-quotes to the unicode equivalent in all three cases, that seems more appropriate.

**Comment by bcmills** [comment]
Yes, the Unicode characters are what I had in mind.

**Comment by agnivade** [comment]
I agree. I have a simpler solution if you may. We can handle this in the template render function inside godoc. With just an additional helper.

Currently, it is this `{{html .Synopsis}}`

We can just port the minimal logic from `go/doc` and have a new helper. Thus making it 
`{{html .Synopsis | commentEscape}}`

So `doc.Synopsis` remains unchanged, and we still get to convert the quotes. Albeit with some very minimal code duplication.

**Comment by bcmills** [comment]
Probably we should factor out the `nice` part from the `HTMLEscape` part: we can convert quotes in the first pass (for `Synopsis` and `ToText`), and then `HTMLEscape` the result.

**Comment by agnivade** [comment]
@bcmills - Could you clarify your comment a bit ? I was looking to get going with this and wasn't fully sure what the consensus was. Did you mean to say we should convert the quotes for all the 3 functions (`ToHTML`, `ToText` and `Synopsis`) ? `HTMLEscape`ing _after_ converting quotes will also convert the `&ldquote;` to ` &amp;ldquote;`.

I believe the primary concern here is that `Synopsis` is used for text and html output both, so converting to html entities will be incorrect for programs expecting text output.

Or did you mean that we should convert to the unicode character directly, for all 3 cases ? That seems to be a clean solution to me.

**Comment by bcmills** [comment]
> Did you mean to say we should convert the quotes for all the 3 functions (`ToHTML`, `ToText` and `Synopsis`) ?

Yes: we should convert the quotes to Unicode characters (`“` and `”`), and if ToHTML wants to convert them further then it can transform `“` to `&ldquote;` and `”` to `&rdquote;`.
