### ISSUE TITLE
missing dot in first path element

### ISSUE THREAD

**Issue by maniLonkar** [golang/go#34245]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.13 darwin/amd64

</pre>

### Does this issue reproduce with the latest release?

yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>
``` go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/lonkar/Library/Caches/go-build"
GOENV="/Users/lonkar/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/lonkar/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.13/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/lonkar/indigo/poc/k8s-cloud-mgr-svc/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5j/3twyy2s95mn2m46hz_35qthrp4gblv/T/go-build924010494=/tmp/go-build -gno-record-gcc-switches -fno-common"
```
### What did you do?

```
go get -u -t github.com/volatiletech/sqlboiler
```
### What did you see instead?
```
go get -u -t github.com/volatiletech/sqlboiler
go: finding golang.org/x/sys latest
go: finding github.com/volatiletech/inflect latest
build github.com/volatiletech/sqlboiler: cannot load bufio: malformed module path "bufio": missing dot in first path element```

**Comment by maniLonkar** [comment]
I used https://ahmadawais.com/install-go-lang-on-macos-with-homebrew/ to setup env & install go. this fixed it

**Comment by aayushrathore** [comment]
for me the issue was resolved after chaning the GOROOT environment variable from "/usr/loca/go/bin" to "/usr/local/go"

OS : Linux centos

**Comment by Logic-Luo** [comment]
可能是goland terminal的问题，我使用goland的terminal，就报can't load package: package go_demo/article3/lib: malformed module path "go_demo/article3/lib": missing dot in first path element
类似的错误，但是使用系统的terminal就没问题

**Comment by FrederickHou** [comment]
> 可能是goland terminal的问题，我使用goland的terminal，就报can't load package: package go_demo/article3/lib: malformed module path "go_demo/article3/lib": missing dot in first path element
> 类似的错误，但是使用系统的terminal就没问题

thank you ,you had better use English to reply it .Hahaha

**Comment by Toplife** [comment]
May be you have different go root path between IDE and default, pls make sure this point..

**Comment by tedyu** [comment]
I am building https://github.com/cluster-api on Mac.
```
$ echo $GOROOT
/Users/yute/homebrew/Cellar/go/1.13.4
```
When I run 'make test', I get
```
build sigs.k8s.io/cluster-api: cannot load bufio: malformed module path "bufio": missing dot in first path element
make: *** [test] Error 1
```
The GOROOT is not under bin dir but I still get the above error.
Does someone have a clue ?

Thanks
