### ISSUE TITLE
x/tools/gopls: add a regression test for adding a new function to a replace target

### ISSUE THREAD

**Issue by segevfiner** [golang/go#40712]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.14.7 darwin/amd64
</pre>

<pre>
# gopls version
golang.org/x/tools/gopls 0.4.4
    golang.org/x/tools/gopls@v0.4.4 h1:8djGYsaZ0ByP0vaXg4T+mnyfDcHpWKSZ+tpQSGv9ahk=
</pre>

VS Code version v1.47.3
vscode-go v0.16.1

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/segev/Library/Caches/go-build"
GOENV="/Users/segev/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/segev/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.14.7/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.14.7/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/b_/c6yh0ksn63d1yy192x2p9f4c0000gn/T/go-build425202633=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?

1. Create two new packages using Go modules:
   ```sh
   mkdir foo && cd foo
   go mod init github.com/segevfiner/foo
   cd ..
   mkdir bar && cd bar
   go mod init github.com/segevfiner/bar
   cd ..
   ```
2. Open VS Code with vscode-go installed and gopls enabled: `code foo bar`
3. Add `replace github.com/segevfiner/bar => ../bar` to module `foo`'s go.mod.
4. Add to module `foo` as `main.go`:
    ```go
    package main

    func main() {

    }
    ```
5. Add to module `bar` as `bar1.go`:
    ```go
    package bar
  
    func Bar1() {

    }
    ```
6. Try to add `foo.Bar1()` to `foo`'s `main.go`, it would work and also auto complete it. (Might need to manually add the import statement)
7. Add to module `bar` as `bar2.go`:
    ```go
    package bar

    func Bar2() {

    }
    ```
8. Try to add `foo.Bar2()` to `foo`'s `main.go`, it would not autocomplete and will fail to compile until you restart the language server.

### What did you expect to see?
Adding new files to replaced packages should work seamlessly, auto-completing, compiling correctly, without requiring a restart of the language server.

### What did you see instead?
It fails to auto-complete, compile etc. (While working correctly with `go build`) until you restart the language server.

**Comment by stamblerre** [comment]
This is actually a known issue which should be resolved at master (https://golang.org/cl/245327).
If you're interested, you can give it a try by downloading master (`GO111MODULE=on go get golang.org/x/tools/gopls@master  golang.org/x/tools@master).

**Comment by segevfiner** [comment]
Trying with (Installed using the provided command):
```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.0.0-20200811215021-48a8ffc5b207 h1:mOy1nNJGN9EIh6lz32XSu+nRN/eQCz6pUy3bNyvpGBc=
```

It's even worse, it's now not finding the module replaced module at all, complaining with:
```
could not import github.com/segevfiner/bar (no package for import github.com/segevfiner/bar)
``` 

While `go build` works correctly.

<details>
<summary><code>gopls -rpc.trace -v check foo.go</code></summary>
<pre>
2020/08/12 18:46:50 Info:2020/08/12 18:46:50 Build info----------
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.0.0-20200811215021-48a8ffc5b207 h1:mOy1nNJGN9EIh6lz32XSu+nRN/eQCz6pUy3bNyvpGBc=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=
    golang.org/x/tools@v0.0.0-20200811215021-48a8ffc5b207 h1:8Kg+JssU1jBZs8GIrL5pl4nVyaqyyhdmHAR4D1zGErg=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.14.7 darwin/amd64


2020/08/12 18:46:50 Info:2020/08/12 18:46:50 go env for /Users/segev/junk/gopls-issue2/foo
(root /Users/segev/junk/gopls-issue2/foo)
(valid build configuration = true)
(build flags: [])
GOMOD=/Users/segev/junk/gopls-issue2/foo/go.mod
GONOPROXY=github.com/OceanCodes
GOPRIVATE=github.com/OceanCodes
GOPROXY=https://proxy.golang.org,direct
GOROOT=/usr/local/Cellar/go/1.14.7/libexec
GO111MODULE=
GOMODCACHE=
GOFLAGS=
GOSUMDB=sum.golang.org
GOCACHE=/Users/segev/Library/Caches/go-build
GONOSUMDB=github.com/OceanCodes
GOPATH=/Users/segev/go
GOINSECURE=

2020/08/12 18:46:50 Info:2020/08/12 18:46:50 go/packages.Load
        snapshot=0
        directory=/Users/segev/junk/gopls-issue2/foo
        query=[./... builtin]
        packages=2

</pre>
</details>

<details>
<summary>Log</summary>
<pre>
[Trace - 18:52:57.669 PM] Sending request 'initialize - (0)'.
Params: {"processId":75662,"clientInfo":{"name":"vscode","version":"1.47.3"},"rootPath":"/Users/segev/junk/gopls-issue2","rootUri":"file:///Users/segev/junk/gopls-issue2","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true,"versionSupport":false,"tagSupport":{"valueSet":[1,2]}},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}},"contextSupport":true},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"isPreferredSupport":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true,"tooltipSupport":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true},"selectionRange":{"dynamicRegistration":true}},"window":{"workDoneProgress":true}},"initializationOptions":{},"trace":"off","workspaceFolders":[{"uri":"file:///Users/segev/junk/gopls-issue2","name":"gopls-issue2"}]}


[Trace - 18:52:57.685 PM] Received response 'initialize - (0)' in 16ms.
Result: {"capabilities":{"textDocumentSync":{"openClose":true,"change":2,"save":{}},"completionProvider":{"triggerCharacters":["."]},"hoverProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"typeDefinitionProvider":true,"implementationProvider":true,"referencesProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","refactor.extract","refactor.rewrite","source.fixAll","source.organizeImports"]},"codeLensProvider":{},"documentLinkProvider":{},"workspaceSymbolProvider":true,"documentFormattingProvider":true,"documentOnTypeFormattingProvider":{"firstTriggerCharacter":""},"renameProvider":{"prepareProvider":true},"foldingRangeProvider":true,"executeCommandProvider":{"commands":["generate","fill_struct","regenerate_cgo","test","tidy","undeclared_name","upgrade_dependency","vendor","extract_variable","extract_function","gc_details"]},"callHierarchyProvider":true,"workspace":{"workspaceFolders":{"supported":true,"changeNotifications":"workspace/didChangeWorkspaceFolders"}}},"serverInfo":{"name":"gopls","version":"Build info\n----------\ngolang.org/x/tools/gopls master\n    golang.org/x/tools/gopls@v0.0.0-20200811215021-48a8ffc5b207 h1:mOy1nNJGN9EIh6lz32XSu+nRN/eQCz6pUy3bNyvpGBc=\n    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\n    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=\n    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\n    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=\n    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=\n    golang.org/x/tools@v0.0.0-20200811215021-48a8ffc5b207 h1:8Kg+JssU1jBZs8GIrL5pl4nVyaqyyhdmHAR4D1zGErg=\n    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=\n    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=\n    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=\n    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=\n\nGo info\n-------\ngo version go1.14.7 darwin/amd64\n\n"}}


[Trace - 18:52:57.718 PM] Sending notification 'initialized'.
Params: {}


[Trace - 18:52:57.719 PM] Sending notification 'textDocument/didOpen'.
Params: {"textDocument":{"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go","languageId":"go","version":1,"text":"package main\n\nimport \"github.com/segevfiner/bar\"\n\nfunc main() {\n\tbar.Bar1()\n\tbar.Bar2()\n}\n"}}


[Trace - 18:52:57.738 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/08/12 18:52:57 Build info\n----------\ngolang.org/x/tools/gopls master\n    golang.org/x/tools/gopls@v0.0.0-20200811215021-48a8ffc5b207 h1:mOy1nNJGN9EIh6lz32XSu+nRN/eQCz6pUy3bNyvpGBc=\n    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=\n    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=\n    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=\n    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=\n    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=\n    golang.org/x/tools@v0.0.0-20200811215021-48a8ffc5b207 h1:8Kg+JssU1jBZs8GIrL5pl4nVyaqyyhdmHAR4D1zGErg=\n    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=\n    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=\n    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=\n    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=\n\nGo info\n-------\ngo version go1.14.7 darwin/amd64\n\n\n"}


[Trace - 18:52:57.739 PM] Received request 'workspace/configuration - (1)'.
Params: {"items":[{"scopeUri":"file:///Users/segev/junk/gopls-issue2","section":"gopls"},{"scopeUri":"file:///Users/segev/junk/gopls-issue2","section":"gopls-gopls-issue2"}]}


[Info  - 6:52:57 PM] 2020/08/12 18:52:57 Build info
----------
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.0.0-20200811215021-48a8ffc5b207 h1:mOy1nNJGN9EIh6lz32XSu+nRN/eQCz6pUy3bNyvpGBc=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.0 h1:/QaMHBdZ26BB3SSst0Iwl10Epc+xhTquomWX0oZEB6w=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.3.0 h1:RM4zey1++hCTbCVQfnWeKs9/IEsaBLA8vTkd0WVtmH4=
    golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208 h1:qwRHBd0NqMbJxfbotnDhm2ByMI1Shq4Y6oRJo21SGJA=
    golang.org/x/tools@v0.0.0-20200811215021-48a8ffc5b207 h1:8Kg+JssU1jBZs8GIrL5pl4nVyaqyyhdmHAR4D1zGErg=
    golang.org/x/xerrors@v0.0.0-20191204190536-9bdfabe68543 h1:E7g+9GITq07hpfrRu66IVDexMakfv52eLZ2CXBWiKr4=
    honnef.co/go/tools@v0.0.1-2020.1.4 h1:UoveltGrhghAA7ePc+e+QYDHXrBps2PqFZiHkGR/xK8=
    mvdan.cc/gofumpt@v0.0.0-20200709182408-4fd085cb6d5f h1:gi7cb8HTDZ6q8VqsUpkdoFi3vxwHMneQ6+Q5Ap5hjPE=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=

Go info
-------
go version go1.14.7 darwin/amd64



[Trace - 18:52:57.768 PM] Sending request 'textDocument/documentSymbol - (1)'.
Params: {"textDocument":{"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go"}}


[Trace - 18:52:57.768 PM] Sending request 'textDocument/documentLink - (2)'.
Params: {"textDocument":{"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go"}}


[Trace - 18:52:57.794 PM] Sending response 'workspace/configuration - (1)' in 54ms.
Result: [null,null]


[Trace - 18:52:57.820 PM] Sending notification '$/cancelRequest'.
Params: {"id":1}


[Trace - 18:52:57.820 PM] Sending request 'textDocument/documentSymbol - (3)'.
Params: {"textDocument":{"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go"}}


[Trace - 18:52:57.836 PM] Received request 'client/registerCapability - (2)'.
Params: {"registrations":[{"id":"workspace/didChangeWatchedFiles-0","method":"workspace/didChangeWatchedFiles","registerOptions":{"watchers":[{"globPattern":"file:///Users/segev/junk/gopls-issue2/**/*.{go,mod,sum}","kind":7}]}}]}


[Trace - 18:52:57.836 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/08/12 18:52:57 go env for /Users/segev/junk/gopls-issue2\n(root /Users/segev/junk/gopls-issue2)\n(valid build configuration = false)\n(build flags: [])\nGOFLAGS=\nGOINSECURE=\nGOPRIVATE=github.com/OceanCodes\nGOCACHE=/Users/segev/Library/Caches/go-build\nGOROOT=/usr/local/Cellar/go/1.14.7/libexec\nGO111MODULE=\nGOMODCACHE=\nGONOPROXY=github.com/OceanCodes\nGOMOD=\nGOPROXY=https://proxy.golang.org,direct\nGONOSUMDB=github.com/OceanCodes\nGOPATH=/Users/segev/go\nGOSUMDB=sum.golang.org\n\n"}


[Trace - 18:52:57.877 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/08/12 18:52:57 go/packages.Load\n\tsnapshot=0\n\tdirectory=/Users/segev/junk/gopls-issue2\n\tquery=[./ builtin]\n\tpackages=2\n"}


[Trace - 18:52:57.917 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/08/12 18:52:57 go/packages.Load\n\tsnapshot=0\n\tdirectory=/Users/segev/junk/gopls-issue2\n\tquery=[./]\n\tpackages=1\n"}


[Trace - 18:52:57.969 PM] Sending response 'client/registerCapability - (2)' in 132ms.
Result: 


[Trace - 18:52:57.969 PM] Received request 'client/registerCapability - (3)'.
Params: {"registrations":[{"id":"workspace/didChangeConfiguration","method":"workspace/didChangeConfiguration"},{"id":"workspace/didChangeWorkspaceFolders","method":"workspace/didChangeWorkspaceFolders"}]}


[Info  - 6:52:57 PM] 2020/08/12 18:52:57 go env for /Users/segev/junk/gopls-issue2
(root /Users/segev/junk/gopls-issue2)
(valid build configuration = false)
(build flags: [])
GOFLAGS=
GOINSECURE=
GOPRIVATE=github.com/OceanCodes
GOCACHE=/Users/segev/Library/Caches/go-build
GOROOT=/usr/local/Cellar/go/1.14.7/libexec
GO111MODULE=
GOMODCACHE=
GONOPROXY=github.com/OceanCodes
GOMOD=
GOPROXY=https://proxy.golang.org,direct
GONOSUMDB=github.com/OceanCodes
GOPATH=/Users/segev/go
GOSUMDB=sum.golang.org


[Trace - 18:52:57.972 PM] Sending notification '$/cancelRequest'.
Params: {"id":3}


[Trace - 18:52:57.972 PM] Sending request 'textDocument/documentSymbol - (4)'.
Params: {"textDocument":{"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go"}}


[Trace - 18:52:57.973 PM] Sending request 'textDocument/foldingRange - (5)'.
Params: {"textDocument":{"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go"}}


[Info  - 6:52:57 PM] 2020/08/12 18:52:57 go/packages.Load
	snapshot=0
	directory=/Users/segev/junk/gopls-issue2
	query=[./ builtin]
	packages=2

[Info  - 6:52:57 PM] 2020/08/12 18:52:57 go/packages.Load
	snapshot=0
	directory=/Users/segev/junk/gopls-issue2
	query=[./]
	packages=1

[Trace - 18:52:57.987 PM] Sending response 'client/registerCapability - (3)' in 17ms.
Result: 


[Error - Received] 18:52:57.988 PM #1 JSON RPC cancelled


[Trace - 18:52:58.007 PM] Sending request 'textDocument/codeLens - (6)'.
Params: {"textDocument":{"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go"}}


[Trace - 18:52:58.041 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/08/12 18:52:58 go/packages.Load\n\tsnapshot=1\n\tdirectory=/Users/segev/junk/gopls-issue2\n\tquery=[./]\n\tpackages=1\n"}


[Info  - 6:52:58 PM] 2020/08/12 18:52:58 go/packages.Load
	snapshot=1
	directory=/Users/segev/junk/gopls-issue2
	query=[./]
	packages=1

[Trace - 18:52:58.167 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/08/12 18:52:58 go/packages.Load\n\tsnapshot=1\n\tpackage_path=\"command-line-arguments\"\n\tfiles=[/Users/segev/junk/gopls-issue2/foo/main.go]\n"}


[Trace - 18:52:58.167 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/08/12 18:52:58 go/packages.Load\n\tsnapshot=1\n\tdirectory=/Users/segev/junk/gopls-issue2\n\tquery=[file=/Users/segev/junk/gopls-issue2/foo/main.go]\n\tpackages=1\n"}


[Info  - 6:52:58 PM] 2020/08/12 18:52:58 go/packages.Load
	snapshot=1
	package_path="command-line-arguments"
	files=[/Users/segev/junk/gopls-issue2/foo/main.go]

[Trace - 18:52:58.167 PM] Received notification 'window/logMessage'.
Params: {"type":1,"message":"2020/08/12 18:52:58 no dep handle: no metadata for github.com/segevfiner/bar\n\tpackage=\"github.com/segevfiner/bar\"\n"}


[Info  - 6:52:58 PM] 2020/08/12 18:52:58 go/packages.Load
	snapshot=1
	directory=/Users/segev/junk/gopls-issue2
	query=[file=/Users/segev/junk/gopls-issue2/foo/main.go]
	packages=1

[Error - 6:52:58 PM] 2020/08/12 18:52:58 no dep handle: no metadata for github.com/segevfiner/bar
	package="github.com/segevfiner/bar"

[Trace - 18:52:58.168 PM] Received response 'textDocument/documentLink - (2)' in 399ms.
Result: [{"range":{"start":{"line":2,"character":8},"end":{"line":2,"character":33}},"target":"https://pkg.go.dev/github.com/segevfiner/bar"}]


[Error - Received] 18:52:58.168 PM #3 JSON RPC cancelled


[Trace - 18:52:58.169 PM] Received response 'textDocument/documentSymbol - (4)' in 196ms.
Result: [{"name":"main","detail":"()","kind":12,"range":{"start":{"line":4,"character":0},"end":{"line":7,"character":1}},"selectionRange":{"start":{"line":4,"character":5},"end":{"line":4,"character":9}}}]


[Trace - 18:52:58.169 PM] Received response 'textDocument/foldingRange - (5)' in 195ms.
Result: [{"startLine":4,"startCharacter":13,"endLine":6,"endCharacter":11}]


[Trace - 18:52:58.169 PM] Received response 'textDocument/codeLens - (6)' in 161ms.
Result: null


[Trace - 18:52:58.206 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/08/12 18:52:58 go/packages.Load\n\tsnapshot=1\n\tpackage_path=\"command-line-arguments\"\n\tfiles=[/Users/segev/junk/gopls-issue2/foo/main.go]\n"}


[Trace - 18:52:58.206 PM] Received notification 'window/logMessage'.
Params: {"type":3,"message":"2020/08/12 18:52:58 go/packages.Load\n\tsnapshot=1\n\tdirectory=/Users/segev/junk/gopls-issue2\n\tquery=[file=/Users/segev/junk/gopls-issue2/foo/main.go]\n\tpackages=1\n"}


[Trace - 18:52:58.207 PM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go","version":1,"diagnostics":[{"range":{"start":{"line":2,"character":7},"end":{"line":2,"character":34}},"severity":1,"source":"compiler","message":"could not import github.com/segevfiner/bar (no package for import github.com/segevfiner/bar)"}]}


[Info  - 6:52:58 PM] 2020/08/12 18:52:58 go/packages.Load
	snapshot=1
	package_path="command-line-arguments"
	files=[/Users/segev/junk/gopls-issue2/foo/main.go]

[Info  - 6:52:58 PM] 2020/08/12 18:52:58 go/packages.Load
	snapshot=1
	directory=/Users/segev/junk/gopls-issue2
	query=[file=/Users/segev/junk/gopls-issue2/foo/main.go]
	packages=1

[Trace - 18:52:59.448 PM] Sending request 'textDocument/documentSymbol - (7)'.
Params: {"textDocument":{"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go"}}


[Trace - 18:52:59.448 PM] Received response 'textDocument/documentSymbol - (7)' in 0ms.
Result: [{"name":"main","detail":"()","kind":12,"range":{"start":{"line":4,"character":0},"end":{"line":7,"character":1}},"selectionRange":{"start":{"line":4,"character":5},"end":{"line":4,"character":9}}}]


[Trace - 18:52:59.495 PM] Sending request 'textDocument/documentLink - (8)'.
Params: {"textDocument":{"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go"}}


[Trace - 18:52:59.495 PM] Received response 'textDocument/documentLink - (8)' in 0ms.
Result: [{"range":{"start":{"line":2,"character":8},"end":{"line":2,"character":33}},"target":"https://pkg.go.dev/github.com/segevfiner/bar"}]


[Trace - 18:52:59.701 PM] Sending request 'textDocument/codeLens - (9)'.
Params: {"textDocument":{"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go"}}


[Trace - 18:52:59.701 PM] Received response 'textDocument/codeLens - (9)' in 0ms.
Result: null


[Trace - 18:52:59.703 PM] Sending request 'textDocument/codeLens - (10)'.
Params: {"textDocument":{"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go"}}


[Trace - 18:52:59.703 PM] Received response 'textDocument/codeLens - (10)' in 0ms.
Result: null


[Trace - 18:52:59.707 PM] Sending request 'textDocument/codeLens - (11)'.
Params: {"textDocument":{"uri":"file:///Users/segev/junk/gopls-issue2/foo/main.go"}}


[Trace - 18:52:59.707 PM] Received response 'textDocument/codeLens - (11)' in 0ms.
Result: null


</pre>
</details>

**Comment by stamblerre** [comment]
It looks like you're opening the `/Users/segev/junk/gopls-issue2` folder as your workspace root, but the `go.mod` file is contained in `/Users/segev/junk/gopls-issue2/foo`. `gopls` at master still expects your module root to be the root of the workspace.

**Comment by segevfiner** [comment]
Oh wait... Dammit VS Code opened the folder instead of the workspace file in it... (Maybe I forgot to save the workspace file)

It looks like the problem still persists now that I opened the proejct under a workspace correctly.

**Comment by stamblerre** [comment]
To clarify, how are you adding the `replace` to your module? I'm not seeing any edits to the module in your log, and if you're doing it in a different editor, you may have actually picked up a file watching bug that was just fixed by https://golang.org/cl/247684 (it's not limited to Windows-specific, even though the CL title says so). I would suggest upgrading to the latest master as of a few minutes ago (`GO111MODULE=on go get golang.org/x/tools/gopls@master golang.org/x/tools@master`) - sorry about the inconvenience!

**Comment by segevfiner** [comment]
In that case, I already had the `replace` in, and just added a file with a new function to the replaced `bar` module.

Will try it later.

**Comment by stamblerre** [comment]
Thanks for the clarification. We can certainly add a regression test for that case.

**Comment by segevfiner** [comment]
Still happening with:
```
golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@v0.0.0-20200812195022-5ae4c3c160a0 h1:IFIrVpsHUpQrihC1kLyMEOjP71pIxfSzKBFR7Qj5Nx4=
```

**Comment by pjweinb** [comment]
resolved. this all works now
