### ISSUE TITLE
x/build/cmd/release: darwin/arm64 installer prompts for installing Rosetta 2

### ISSUE THREAD

**Issue by usmannajib** [golang/go#43422]
### What version of Go are you using (`go version`)?
1.16beta1
<pre>
$ go version

</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?
MacOS Big Sur on arm64 M1

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env

</pre></details>

### What did you do?
Ran installation

### What did you expect to see?
The installer should have installed Go in native M1 mode.

### What did you see instead?
The installer asked for Rosetta to be installed as a mandatory install dependency.

**Comment by cherrymui** [comment]
Just to be sure, is https://golang.org/dl/go1.16beta1.darwin-arm64.pkg the installer you used?

cc @dmitshur

**Comment by usmannajib** [comment]
Yes take a look at the screenshot below
![image](https://user-images.githubusercontent.com/4241705/103313562-463a0000-49d5-11eb-8e8a-5ed90350cb81.png)

**Comment by dmitshur** [comment]
Thanks for reporting. Perhaps there's some configuration in the installer causing macOS to think Rosetta will be needed, when that shouldn't be the case. We'll take a look.

After installing, does `go version` output end with "darwin/arm64"?

**Comment by dmitshur** [comment]
The problem may be that we're not including a `hostArchitectures` property in the installer Distribution options:

```
$ pkgutil --expand go1.16beta1.darwin-arm64.pkg out
$ cat out/Distribution | grep options
    <options customize="never" allow-external-scripts="no"/>
```

It likely needs to be set to a value that includes `arm64`:

```
<options hostArchitectures="arm64" customize="never" allow-external-scripts="no"/>
```

CC @golang/release, @markmentovai.

**Comment by usmannajib** [comment]
I actually didn't install it as I wanted a "pure" experience 😄

I am testing with 11.1

Let me know if it helps to actually install it.

**Comment by dmitshur** [comment]
Thanks.

We should fix this in time for the next pre-release of Go 1.16. If you'd like, you can wait until then, but you certainly don't have to. This issue affects only the installer, the actual Go distribution is already built for ARM64. You can also use the go1.16beta1.darwin-arm64.tar.gz archive to avoid having to install Rosetta 2.

**Comment by usmannajib** [comment]
@dmitshur Thank you

**Comment by dmitshur** [comment]
I tested the change described in https://github.com/golang/go/issues/43422#issuecomment-752264869 by making use of `pkgutil --expand` and `pkgutil --flatten` to adjust the distribution XML:

```
$ pkgutil --expand go1.16rc1.darwin-arm64.pkg out
$ $EDITOR out/Distribution  # set hostArchitectures="arm64" in options
$ pkgutil --flatten out go1.16rc1.darwin-arm64-edited.pkg
```

(This process strips the signing, but that's not a problem for the purpose of testing the change described here.)

I tested this on a Mac without Rosetta 2 installed (thanks @cagedmantis). Prior to explicitly setting hostArchitectures, Rosetta 2 was required and the installer would not proceed without it. After setting it, Go was successfully installed without Rosetta 2.

It also had the added benefit of reporting "Go can't be installed on this computer." if the ARM64 installer is opened on an Intel-based Mac (previously, the ARM64 installer would run without letting the user know it's the wrong architecture, but then the installed distribution wouldn't run because Intel-based Macs can't run arm64 binaries).

We've updated our release process to apply this change, so the next Go 1.16 release will have this fix. Thanks again for the report. Closing.

**Comment by ifamakes** [comment]
Hi. this still happens to me on my M1 Mac with version 1.17.

**Comment by dmitshur** [comment]
@ifamakes I've checked the `Distribution` file in go1.17.darwin-arm64.pkg, and it still has `hostArchitectures="arm64"` set, so that hasn't regressed on our side.

Since this issue has been closed for a good while, I think we should treat this as a possible new problem. Can you please file a new issue that references this one, and provide more information, such as what macOS version you've tested with. Thank you.
