### ISSUE TITLE
x/tools/gopls: do not suggest names from unimportable internal packages

### ISSUE THREAD

**Issue by butuzov** [golang/go#44890]
### Describe the bug

__Getting internal packages to show up in autocomplete of absolutely unrelated projects.__

### Notes

There are nested module ( with different import path) in workspace `a uses b`, `b located (temporary) under a`, while in __b__ getting __e__ in autocomplete. __a__ and __b__ not use __e__, __b__ uses something that uses _c_
    - a (domain/a)
    - b (domain/b)  
    - c (domain/c)
    - e (domain/c/internal/e)

### Screenshots or recordings

![image](https://user-images.githubusercontent.com/651824/110061306-10681d80-7d70-11eb-94ca-8251d7e2aa31.png)

### What version of Go, VS Code & VS Code Go extension are you using?
```shell
 > gopls version
golang.org/x/tools/gopls v0.6.6
    golang.org/x/tools/gopls@v0.6.6 h1:GmCsAKZMEb1BD1BTWnQrMyx4FmNThlEsmuFiJbLBXio=
 > go version
go version go1.16 darwin/amd64
 > code --version
1.53.2
622cb03f7e070a9670c94bae1a45d78d7181fbd4
x64
```

**Comment by Southclaws** [comment]
Stumbling across this a year later, I'm running into this constantly and it ends up costing more time than it saves.

Whenever I type `uuid.UUID` or related APIs of this package from Google, I _always_, without fail, get `gofrs/uuid` imported. I've deleted this from my system, it's not used in any of my projects as I use Google's implementation but I can't seem to get gopls to stop suggesting this package. It must be cached somewhere, how can I delete the cache?

**Comment by hyangah** [comment]
I also noticed gopls is suggesting internal packages from Go sdk too. 
(I am currently using gopls v0.12.1) 

![Screenshot 2023-06-08 at 2 07 05 PM](https://github.com/golang/go/assets/4999471/49c0fdf8-fe21-42b3-9a6a-937ca7479cca)

**Comment by pjweinb** [comment]
I believe this is fixed in the next gopls release.

**Comment by pjweinb** [comment]
I propose closing this issue.

**Comment by gudvinr** [comment]
> I believe this is fixed in the next gopls release.

Can you share CL or commit where it's fixed?

**Comment by gudvinr** [comment]
> Change https://go.dev/cl/701635 mentions this issue: `gopls/internal/golang/completion: don't offer internal std packages`

According to description it doesn't resolve the issue completely:
> don't offer internal **std packages**

In OP it's stated that non-std packages outside of relevant package also being suggested.

**Comment by adonovan** [comment]
> In OP it's stated that non-std packages outside of relevant package also being suggested.

Indeed, but the logic now actually implements the general check (which, happily, is simpler).
