### ISSUE TITLE
x/tools/analysis/passes/tests: report examples with misplaced Output comments

### ISSUE THREAD

**Issue by ameowlia** [golang/go#48362]
### What version of Go are you using (`go version`)?
<pre>
go version go1.17 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/adowns/Library/Caches/go-build"
GOENV="/Users/adowns/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/adowns/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/adowns/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/Users/adowns/workspace/text/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/4c/1b3s36l94blb6xg1_4p_13800000gn/T/go-build2465748359=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

### What did you do?
I ran this test in a test file:

```
func ExampleThisTestShouldNotPass() {
	fmt.Println("meow")

	// Output:
	// bark

	// TODO: foo bar
}

```

### What did you expect to see?
The test fail

### What did you see instead?
The test passed.

I saw this in a real example with the ExampleMatcher [here](https://github.com/golang/text/blob/383b2e75a7a4198c42f8f87833eefb772868a56f/language/examples_test.go#L341), which I reported in  https://github.com/golang/go/issues/48361.

**Comment by smasher164** [comment]
Also reproduces on the playground: https://play.golang.org/p/0wPM6durES5.

**Comment by ALTree** [comment]
IMO this is working as intended, the `testing` package documentation says:

> Example functions may include a concluding line comment that begins with "Output:" 

I your example the `Output` line comment is not "concluding" so the Example is not processed as an check-output one.

**Comment by smasher164** [comment]
@ALTree In that case, the broken examples should probably just be addressed by moving the non-`Output` comments before the `Output` comment.

**Comment by ameowlia** [comment]
> IMO this is working as intended

@ALTree: I agree, but it worries me that this allowed a broken example to be around for 4 years. 

Interestingly, it only fails this way when there is another _comment_ after the `output`. See here where it still fails when it is more code after the output: https://play.golang.org/p/RRN7vl8KayA

**Comment by smasher164** [comment]
@ameowlia I agree that this is behavior that is subtle and hard to catch. What if the testing tool's heuristic was changed to only process `CommentGroup`s that begin with `Output:`? It would be able to ignore that TODO comment, and the output comment could be placed anywhere in the function, without affecting the test result.

**Comment by ameowlia** [comment]
> What if the testing tool's heuristic was changed to only process CommentGroups that begin with Output:?

@smasher164  - I looked into this today ([code here](https://github.com/golang/go/blob/181e8cde301cd8205489e746334174fee7290c9b/src/go/doc/example.go#L116-L134)). I would like to try to contribute this if others think it is an acceptable solution.

The main argument against this fix that I can see is "what happens if an example has multiple output commentblocks"? In that case I would suggest returning the first one and ignoring later ones. Multiple outputs seems like flagrant disregard for the spec. Adding a comment at the end (the issue I reported here) seems like an accident that would be nice to protect against.

Alternatively we could add a go/vet warning to make sure that output commentblocks are always the last commentblock. This seems a little heavy handed though.

**Comment by zpavlinovic** [comment]
Regarding the vet approach, this would at least need to satisfy the requirement of high frequency. It is not clear at the moment how frequent this issue is.

Another approach is to perhaps make the documentation more clear.

**Comment by smasher164** [comment]
> It is not clear at the moment how frequent this issue is.

Yeah, the bug in x/text/language's example might be a rare exception. Running an `*analysis.Analyzer` on a corpus of open source code might give a better idea of how frequently this pops up. Without that information, it seems heavy handed both to change how comments are processed and to add a vet check.

Updating the documentation seems like a good option. Right now, testing says
> Example functions may include a concluding line comment that begins with "Output:" and is compared with the standard output of the function when the tests are run. (The comparison ignores leading and trailing space.)

**Comment by zpavlinovic** [comment]
@matloob

**Comment by ameowlia** [comment]
I wrote a parser, ran it against this repo, and found one example: https://github.com/golang/go/issues/48494. I plan on running it against `golang.org/x/...` repos today. 

❓ @smasher164 - Any advice on how to run against a "corpus of open source code"?

**Comment by smasher164** [comment]
> ❓ @smasher164 - Any advice on how to run against a "corpus of open source code"?

I typically run tools like that over my `GOPATH`, assuming I have a decent number of packages installed. For instance, this is what I did for the string(int) conversion vet check: https://github.com/golang/go/issues/32479#issuecomment-570003094, https://github.com/golang/go/issues/32479#issuecomment-570078978.

I guess nowadays with go modules, I'd run that over the `vendor` directory in some project that imports a large number of dependencies? I couldn't find an official way to list all major versions of modules in the cache, but this might work:
```bash
$ find $(go env GOMODCACHE) -type f -name go.mod |
while read fname; do echo "${fname#$(go env GOMODCACHE)/}" |
cut -f1 -d"@"; done |
sort -u
```

**Comment by jayconrod** [comment]
I think a vet check is the right place to fix this. See [`checkExample`](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.1.6:go/analysis/passes/tests/tests.go;l=111) in `golang.org/x/tools/go/analysis/passes/tests`. It already checks that examples have the right name and signature. It could check that the `// Output:` comment is in the right place, too.

**Comment by zpavlinovic** [comment]
> I think a vet check is the right place to fix this. See [`checkExample`](https://cs.opensource.google/go/x/tools/+/refs/tags/v0.1.6:go/analysis/passes/tests/tests.go;l=111) in `golang.org/x/tools/go/analysis/passes/tests`. It already checks that examples have the right name and signature. It could check that the `// Output:` comment is in the right place, too.

Good point. I guess we don't need to worry about the frequency of this pattern because we are just extending an existing checker with a simple logic?

**Comment by jayconrod** [comment]
> Good point. I guess we don't need to worry about the frequency of this pattern because we are just extending an existing checker with a simple logic?

Right, exactly. Just reporting something that was already buggy.

**Comment by ameowlia** [comment]
I ended up running the parser against the [top 1000 open source golang repos based on stars](https://github.com/kaxap/arl/blob/master/README-Go.md) and I found 5 additional instances of the bug(after removing duplicates from vendoring).

| Project Name |  Links |
|-----------|-----------|
| [golang/go](https://github.com/golang/go) | [buggy test](https://github.com/golang/go/blob/9e60c371473ff15eb4b13981721b29f62e1d862c/src/cmd/compile/internal/types2/example_test.go#L191-L247), [github issue](https://github.com/golang/go/issues/48494) |
| [golang/text](https://github.com/golang/text) | [buggy test](https://github.com/golang/text/blob/383b2e75a7a4198c42f8f87833eefb772868a56f/language/examples_test.go#L246-L341), [github issue](https://github.com/golang/go/issues/48361) |
| [miekg/dns](https://github.com/miekg/dns) | [buggy test](https://github.com/miekg/dns/blob/4e8fe099f421b9920a5f2d5ec95579453796140b/example_test.go#L121-L146), [github issue](https://github.com/miekg/dns/issues/1299)  |
| [m3db/m3](https://github.com/m3db/m3) | [buggy test](https://github.com/m3db/m3/blob/9fea52cc91b4f7af9a126c6f9bebcffa475db1fa/src/x/pool/example_test.go#L39-L61), [github issue](https://github.com/m3db/m3/issues/3763) |
| [cuelang/cue](https://github.com/cuelang/cue) -> [cue-lang/cue](https://github.com/cue-lang/cue ) | [buggy test](https://github.com/cue-lang/cue/blob/e8550b89779d293bbc9b530d2c4c9f9cf4c6f3d0/cue/examplecompile_test.go#L24-L51), [github issue](https://github.com/cue-lang/cue/issues/1267) |
| [zalando/skipper](https://github.com/zalando/skipper)| [buggy test](https://github.com/zalando/skipper/blob/11b7acad09fc7c0873b3c2cd4779f539a8aa9bcd/eskip/example_test.go#L24-L78), [github issue](https://github.com/zalando/skipper/issues/1860) |
| [smartcontractkit/chainlink](https://github.com/smartcontractkit/chainlink)| [buggy test](https://github.com/smartcontractkit/chainlink/blob/be421404e3ca283cb8d403753adf6e72bbff9f3a/core/main_test.go#L14-L57), [github issue](https://github.com/smartcontractkit/chainlink/issues/5066) |

@jayconrod  - I'll start working on extending the checkExample vet check. Thank you for the point in the right direction.

**Comment by jayconrod** [comment]
@ameowlia Nice finds. I bet there are a lot more out there, too. Thanks for working on this.
