### ISSUE TITLE
x/net/http2: http.Server.WriteTimeout does not fire if the http2 stream's window is out of space.

### ISSUE THREAD

**Issue by davecheney** [golang/go#49741]
### What version of Go are you using (`go version`)?

<pre>
$ go version 1.17.3

</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

```
package main

import (
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"strings"
	"time"
)

func handler(w http.ResponseWriter, r *http.Request) {
	data := strings.Repeat("x", 1<<16)
	tick := time.NewTicker(1 * time.Millisecond)
	defer tick.Stop()
	for {
		select {
		case <-tick.C:
			n, err := io.WriteString(w, data)
			log.Printf("wrote %d, err %v", n, err)
			if err != nil {
				return
			}
		case <-r.Context().Done():
			log.Printf("context cancelled")
			return
		}
	}
}

func main() {
	sv := httptest.NewUnstartedServer(http.HandlerFunc(handler))
	sv.EnableHTTP2 = true
	sv.Config.WriteTimeout = 1 * time.Second
	sv.StartTLS()

	resp, err := sv.Client().Get(sv.URL + "/")
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	select {} // block forever
}
```

This program creates a HTTP2 service which fills the HTTP/2 stream's response window by failing to consume any data from the response body. The write deadline should fire after 1 second and terminate the response. It does not.

### What did you expect to see?

If the `tick` rate is increased to 100ms, the write timeout fires
```
(~/devel/http2bug) % go run .
2021/11/23 13:03:12 wrote 65536, err <nil>
2021/11/23 13:03:13 wrote 65536, err <nil>
2021/11/23 13:03:13 wrote 65536, err <nil>
2021/11/23 13:03:13 wrote 65536, err <nil>
2021/11/23 13:03:13 wrote 65536, err <nil>
2021/11/23 13:03:13 wrote 65536, err <nil>
2021/11/23 13:03:13 wrote 65536, err <nil>
2021/11/23 13:03:13 wrote 65536, err <nil>
2021/11/23 13:03:13 wrote 65536, err <nil>
2021/11/23 13:03:13 wrote 4096, err http2: stream closed
```

### What did you see instead?

If `tick` is left at 1 ms, permitting it to fill the stream's response window, `handler` blocks, no timeout is reported on either the client or the server side.

```
(~/devel/http2bug) % go run .
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>
2021/11/23 13:03:56 wrote 65536, err <nil>

// output stops
```

/cc @neild @bradfitz

**Comment by aojea** [comment]
> If `tick` is left at 1 ms, permitting it to fill the stream's response window, `handler` blocks, no timeout is reported on either the client or the server side.

interestingly, you can increase the tick, it always block when it writes 64 blocks. If I divide by 2 the data `data := strings.Repeat("x", 1<<15)` it blocks when it writes 128 blocks.

It seems that something blocks when it has 64x65536 = 4MB, the bytes.Buffer?
https://github.com/golang/go/blob/2ebe77a2fda1ee9ff6fd9a3e08933ad1ebaea039/src/bytes/buffer.go#L16

**Comment by davecheney** [comment]
> It seems that something blocks when it has 64x65536 = 4MB, the bytes.Buffer?

I believe that is the streams window, as the client is not reading from the response stream it will not be triggering window updates to refill the window

**Comment by aojea** [comment]
> I believe that is the stream's window, as the client is not reading from the response stream it will not be triggering window updates to refill the window

```diff
37a38
	resp, err := sv.Client().Get(sv.URL + "/")
> 	log.Printf("Request resp %v, error: %v", resp, err)
	if err != nil {
		log.Fatal(err)
	}
```

I didn't realize that the client exits successfully , is the server handler that keeps hanging
```
go run ~/tmp/main.go 
2021/11/25 16:03:08 Reqest resp &{200 OK 200 HTTP/2.0 2 0 map[Content-Type:[text/plain; charset=utf-8] Date:[Thu, 25 Nov 2021 15:03:08 GMT]] {0xc00019a600} -1 [] false false map[] 0xc00019e000 0xc000150420}, error: <nil>
2021/11/25 16:03:08 wrote 65536, err <nil>
2021/11/25 16:03:08 wrote 65536, err <nil>
```

**Comment by aojea** [comment]
@davecheney you are right, I've found the problem, is the stream window as you say

I'll send a patch so you can review

**Comment by davecheney** [comment]
@mknyszek I see you're landing a bunch of HTTP/2 fixes for 1.17.4. Could I ask you to consider this one for inclusion. Thank you.

**Comment by mknyszek** [comment]
@davecheney It might be a little late, we just met today to go over the backport issues to cherry-pick, and generally we only include those whose changes have already landed. I think this should probably wait until the next minor release (that is in a month), but I'll see if @neild has any opinions on this. If it's severe enough it may warrant trying to get it in this one.

**Comment by neild** [comment]
Nice catch for a subtle bug. CL looks good to me, but as this fix is just landing and the bug is long-standing I think it's too late for 1.17.4.

**Comment by davecheney** [comment]
Thanks for considering it. I can stick with x/net/http2 til the next minor ships

**Comment by mknyszek** [comment]
(Moving to backlog as part of triage, just because this isn't a new issue in 1.18.)

**Comment by mknyszek** [comment]
(Er, actually it seems like y'all plan to fix this, I'm gonna guess in 1.19? Moving to 1.19 milestone.)

**Comment by davecheney** [comment]
@mknyszek i'd prefer to not have to wait til 1.19 for this to be backported to net/http. Is it possible this could be included in the next x/net/http2 backport into 1.17.6, or at least 1.18.1?

**Comment by mknyszek** [comment]
@davecheney The backport for 1.17 will go in sooner, and we'll file a separate issue for that. It'll definitely go into 1.18.1 when the milestone is opened, I just mean that the fix on tip will land in the 1.19 *cycle* (so when the tree opens in February).

@gopherbot Please open a backport issue for Go 1.17.

**Comment by toothrot** [comment]
@neild @mknyszek @davecheney Because this issue was fixed before go1.18rc1, and we want it in the 1.18.1 release, we should actually just update the vendored x/net in the `go` repo for 1.18, and ensure this is part of the 1.18 release.

In that case, the steps would be:
- backport to 1.16 (in addition to the 1.17 backport)
- close #49922 
- update the vendored x/net on go's master branch

**Comment by cagedmantis** [comment]
@gopherbot Please open a backport issue for Go 1.16.

**Comment by cagedmantis** [comment]
Backport issue(s) opened: #50449 (for 1.16)

Remember to create the cherry-pick CL(s) as soon as the patch is submitted to master, according to https://golang.org/wiki/MinorReleases.

**Comment by FrankReh** [comment]
The original test case given above still does not timeout after a second when building with go1.17.6, even though the commit that fixed golang.org/x/net was cherry picked.

I've seen the failure with both Darwin and Linux builds.

I can get the test case to timeout correctly if I use the latest golang.org/x/net package and modify main with the ConfigureServer call:

``` go
package main

import (
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"strings"
	"time"

	"golang.org/x/net/http2"
)

func handler(w http.ResponseWriter, r *http.Request) {
	data := strings.Repeat("x", 1<<16)
	tick := time.NewTicker(1 * time.Millisecond)
	defer tick.Stop()
	for {
		select {
		case <-tick.C:
			n, err := io.WriteString(w, data)
			log.Printf("wrote %d, err %v", n, err)
			if err != nil {
				return
			}
		case <-r.Context().Done():
			log.Printf("context cancelled")
			return
		}
	}
}

func main() {
	sv := httptest.NewUnstartedServer(http.HandlerFunc(handler))
	err := http2.ConfigureServer(sv.Config, &http2.Server{})
	if err != nil {
		log.Fatal(err)
	}
	sv.EnableHTTP2 = true
	sv.Config.WriteTimeout = 1 * time.Second
	sv.StartTLS()

	resp, err := sv.Client().Get(sv.URL + "/")
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	select {} // block forever
}
```

The go.mod:
```
module main

go 1.17

require golang.org/x/net v0.0.0-20220127200216-cd36cc0744dd

require golang.org/x/text v0.3.7 // indirect
```

But what's interesting is I can also get the hung write to timeout correctly without the golang.org/x/net package, but I had
to modify the go net package source (and rebuild go) to export the http2ConfigureServer function. By calling that in place of the http2:ConfigureServer call above, that also causes the blocked write to timeout correctly.

**Comment by ianlancetaylor** [comment]
Reopening.  CC @neild

**Comment by aojea** [comment]
I've found the problem, there is an inconsistency on the default writeScheduler chosen:

The fix for the WriteTimeout issue was  in the `RandomWriteScheduler`, that is chosen if you use configureTransport directly

https://github.com/golang/go/blob/a5c0b190809436fd196a348f85eca0416f4de7fe/src/net/http/h2_bundle.go#L4114-L4118

However, when http2 is configured automatically, it uses a different WriteScheduler, that may have the same issue than the other WriteScheduler

https://github.com/golang/go/blob/a5c0b190809436fd196a348f85eca0416f4de7fe/src/net/http/server.go#L3296-L3311

So, I think that there are 2 things to fix here:
- a bug in NewPriorityWriteScheduler
- consistency defaulting the WriteScheduler

@neild @ianlancetaylor I can take on this if you want.

**Comment by aojea** [comment]
Submitted a patch for fixing the scheduler http2NewPriorityWriteScheduler bug.

What should be the default scheduler `http2NewPriorityWriteScheduler()` or ` http2NewRandomWriteScheduler()`
