### ISSUE TITLE
go install OR docs inconsistent to install multiple versions

### ISSUE THREAD

**Issue by staticdev** [golang/go#54477]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.15.15 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/user/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/opt/go/1.18"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/opt/go/1.18/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build482777503=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?

1. cd to a go module.
2. execute install as instructed in https://go.dev/doc/manage-install

```sh
$ go install golang.org/dl/go1.17.0@latest
```

### What did you expect to see?

```
$ go1.17.0 version
> return a value
```

### What did you see instead?

```
> go install golang.org/dl/go1.17.0@latest
> package golang.org/dl/go1.17.0@latest: can only use path@version syntax with 'go get'
$ go1.17.0 version
> 
```

**Comment by staticdev** [comment]
@seankhliao it is not a question, I updated it with currently supported versions, still does not work. Could you please reopen?

**Comment by seankhliao** [comment]
The linked "go install command" describes how the install works.
This is a config issue for your local system.

**Comment by staticdev** [comment]
> The linked "go install command" describes how the install works. This is a config issue for your local system.

As I have shown in the description of my issue, I've read the linked documentation and followed exactly what is described having a different result from what the documentation mentions.

What evidence do you have it is a config issue with my local system and not a bug or problem with the documentation? Can you elaborate on that?

**Comment by ALTree** [comment]
@staticdev as you probably know, when you type `$ command` in your terminal emulator your shell will search for an executable named `command` in the directories specified in your system's [`PATH` variable](https://en.wikipedia.org/wiki/PATH_(variable)). 

The reason you're getting "go1.19: command not found" errors is that you didn't add the `GOPATH/bin` folder to your system PATH variable, so binaries installed by `go install` are not visible to your shell.

From the [`go install` doc page](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies) (also linked in the page you're reading):

> Executables are installed in the directory named by the GOBIN environment variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH environment variable is not set. 

In this case, and `export PATH=$PATH:$GOPATH/bin` should fix the issue.

**Comment by staticdev** [comment]
@ALTree the installation indeed goes to /home/user/go, but `export PATH=$PATH:$GOPATH/bin` does not fix. `go env` returns the value `GOPATH="/home/user/go"` but this variable is NOT on my `env` for some reason even if I try to print it:

```
echo $GOPATH
> nothing
```

Shouldn't `go install` be setting it?

**Comment by ALTree** [comment]
You can set `GOPATH` to override it, otherwise it defaults to $HOME/go and you'll need to add that to $PATH to make `go install` binaries visible.

**Comment by staticdev** [comment]
Looks like there is problem with "go env", since I did not set `GOPATH`, my `go env` shows `GOBIN` empty and `GOPATH` as `/home/user/go`. In this case `go install` should install in `GOROOT`, right?

This is what I understood from https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies

**Comment by ALTree** [comment]
> In this case go install should install in GOROOT, right?

No, read the text carefully

> GOBIN [..] defaults to [..] $HOME/go/bin if the GOPATH environment variable is not set.

So `go install` puts stuff in $HOME/go/bin. You can add that to your PATH.

**Comment by staticdev** [comment]
@ALTree it is not clear at all! I read carefully, why then GOROOT is mentioned in the documentation right after?

`Executables in $GOROOT are installed in $GOROOT/bin or $GOTOOLDIR instead of $GOBIN.`
