### ISSUE TITLE
x/exp/apidiff: panic on latest compiler version

### ISSUE THREAD

**Issue by jba** [golang/go#56162]
apidiff does not understand something about how go/types represents things in the latest version (pre 1.20). 
Its test needs a "go 1.18" directive in the go.mod file; after that, apidiff panics.

**Comment by jba** [comment]
This is a problem with a tool that is not part of the main toolchain, and is explicitly labeled experimental (because it's in the exp repo). So it should not affect the actual Go release. But some people do rely on it (it is part of their release process, for instance).

**Comment by findleyr** [comment]
I think this changed with the unified IR importer. If apidiff broke, it is safe to assume that other tools will break too.

It's also somewhat problematic that go/types (AFAIK) still sets a named receiver, but there are other examples of where imported packages are not-quite-identical to type-checked packages, for example they don't have function scopes.

@mdempsky @adonovan @griesemer are we comfortable with the breakage here?

**Comment by adonovan** [comment]
(At first I thought this was a discussion about throwing away Var names from receivers, parameters, and results, which is fair game. But we're really talking about using the underlying unnamed interface type for interface methods.)

This seems to be a regression of https://github.com/golang/go/issues/13829, and I think it should be fixed again.

**Comment by mdempsky** [comment]
Can we first confirm this issue is still present and get further details on what's failing? I've never used apidiff. I don't know how to begin to reproduce this issue.

go/internal/gcimporter does set named interface receivers. I forget if that CL was ported to x/tools though; maybe not.

**Comment by findleyr** [comment]
Looks like it was fixed in https://go.dev/cl/421255, but I am guessing the apidiff module does not yet see that commit.

**Comment by findleyr** [comment]
In case this CL isn't yet in x/tools@latest, I believe the new release automation is _about_ to tag the next version of x/tools. @jba you may need to upgrade to a pseudoversion, or wait ~days to upgrade to x/tools@v0.2.0.

**Comment by jba** [comment]
apidiff is not its own module; it is part of golang.org/x/exp.
Should I make it its own module? Other subdirectories of exp are.
But there is also cmd/apidiff, which unfortunately is not under apidiff. It is a small binary, but it's what uses golang.org/x/tools/go/gcexportdata and .../go/packages.
Upgrading all of exp is also a reasonable choice, so one alternative is to do nothing.

**Comment by findleyr** [comment]
I think we should upgrade x/exp once x/tools is tagged.

@golang/release are working on automated tagging, but I believe x/exp is excluded.
