### ISSUE TITLE
x/tools/gopls: annotations for implementations of interfaces

### ISSUE THREAD

**Issue by BIKA-C** [golang/go#56695]

**Comment by galkowskit** [comment]
> I found an extension that does kinda the opposite which is not very helpful in most scenario: [galkowskit/go-interface-annotations](https://github.com/galkowskit/go-interface-annotations)

It actually had bidirectional code lens, but only for structs. I released a 0.1.0 version that makes it work on non-struct types as well. Underneath, it's using the "Find Implementations" and "Find References" VS Code feature, so the `gopls` version would still be miles better. But it should tide people over until then, if they really need this feature. :)

**Comment by adonovan** [comment]
We are in the process of rewriting gopls' `implementations` feature so that it uses a global persistent index. Currently gopls must type-check every package in the workspace (since any package might define a type that satsifies an arbitrary interface), but in the next month or so we expect that gopls will be able to make cache hits in the persistent index without type-checking, so it should dramatically reduce the cost of an `implementations` query in a large workspace on all but the very first run after installing a new gopls executable.

At that point it might become feasible to implement something like this feature request as a code lens.

**Comment by adonovan** [comment]
> @adonovan Hope you don't mind us commenting in this [repository.](https://github.com/golang/go/issues/url)

No, of course, that's fine.

Where can I find the source code for Tooltitude? The download page took me to an obfuscated executable, and of course there's no way I'm going to run that on my machine. Alternatively, is there any documentation about how it relates to gopls?

**Comment by marlongerson** [comment]
Would be nice to have a gutter icon as well like in Goland.

**Comment by tkg-codes** [comment]
Any updates on this one? I tried to implement something for neovim, but I can't seem to get `gopls` to return what I what, so I guess this is still not implemented. Is that correct?

**Comment by Tesohh** [comment]
> > I found an extension that does kinda the opposite which is not very helpful in most scenario: [galkowskit/go-interface-annotations](https://github.com/galkowskit/go-interface-annotations)
> 
> It actually had bidirectional code lens, but only for structs. I released a 0.1.0 version that makes it work on non-struct types as well. Underneath, it's using the "Find Implementations" and "Find References" VS Code feature, so the `gopls` version would still be miles better. But it should tide people over until then, if they really need this feature. :)

i think they added this in the extension, but still, it would be nice to have these types of features in the go extension by default

**Comment by tkg-codes** [comment]
> i think they added this in the extension, but still, it would be nice to have these types of features in the go extension by default

https://github.com/tkg-codes/go-interface-annotations <- I have a hacked solution in my VSCode extension. But it might start to chug on large codebases, I haven't tested it thoroughly.

I would still like to have this be supported by `gopls` instead of just VSCode, as otherwise I don't think support for Vim/Neovim, Sublime, Zed et cetera is possible. If this feature would be supported by `gopls` directly then it would be much more performant.

**Comment by adonovan** [comment]
gopls now has an index of implementations, so it can compute the corresponding types for a single type efficiently, but this feature needs the ability to query the correspondences for every type in the file. There's still substantial work to do to make an efficient batch-parallel implementations query. Until then, the client side code lens implementation is as good as one can expect, although of course it works only in VS Code.

**Comment by tkgalk** [comment]
Unrelated, but in case someone gets here by googling and sees your last post about VSCode.

I'm working on a neovim version as well, and for anyone interested there is already lap-lens.nvim, too. :) 

So while gopls version would be better, there are client-side solutions out there.

**Comment by adonovan** [comment]
Someone kindly offered (via email) to contribute this feature. For posterity and transparency, I've shared part of my response to them below.

--

I think this particular feature may be quite challenging to implement efficiently, even now that we've completed the changes we were planning to the architecture of gopls. (In fact, our changes may actually have made this problem more difficult because it is more expensive to join type information from an arbitrary pair of packages.) You may find this [blog post](https://go.dev/blog/gopls-scalability) and [this talk](https://www.youtube.com/watch?v=3muw_bukfRA&list=PLeGxIOPLk9ELjez2zb2BtvndVP5ibT-v-&index=8&app=desktop) a useful introduction to some of the recent design changes.

Each of the proposed annotations on a type requires a global query to compute the set of interfaces that it implements, or is implemented by. (Yes, the "find implementations" algorithm works both ways.) When I say global, I mean every package, not just the forward or reverse dependencies, because interfaces can be implemented by types that aren't dependencies in either direction. And any change to any file can in principle invalidate the information previously computed, so it's far from clear to me what the invalidation story is for this feature.

This is unlike most other features, which are either a property of forward dependencies, e.g. diagnostics, type information, static analysis, etc, which are served by the index; or of reverse information, e.g. references, also served from an index; or both, e.g. rename, which requires type checking the entire reverse closure (which is expensive, but the feature is infrequently used).

A more achievable goal might be to report only the relationships between each declared type and some other type mentioned in the same package, so for example,  os.File would say "implements io.Reader, io.Writer, ... and perhaps others", and the "perhaps others" part could be a link that activates the expensive global query to compute the definitive answer for that particular type at that moment. In order to implement that, you would just need to gather the set of "interesting" types after type checking, compute the pairwise implements relation, and record the set of matches in the source.Package.


--

**Comment by findleyr** [comment]
@adonovan I'm not sure this is so infeasible. We already keep a global index of package data live in-memory: the set of type checking diagnostics, and we have a serializable format for method sets. Suppose we also, as part of analyzing a package, kept the method set index in memory (IIRC, the serialized method set data is quite small).  How expensive would it be to, for all types declared in a single file (i.e. within the context of a codelens request), cross reference this method set index?  Suppose also that a small false positive rate were acceptable, as I think may be the case here (or we could detect potential false positives and re-type check a small number of packages to eliminate them).

**Comment by JulianGuSM** [comment]
Any updates on this one?

**Comment by caozhuozi** [comment]
!

**Comment by gowtham-swiggy** [comment]
@gopherbot any update on this. This will be a helpful feature

**Comment by adonovan** [comment]
No direct progress on this issue, sorry. However, we just (moments ago) merged a new feature, support for Type Hierarchy, which allows you to browse named types by their subtype/supertype relationship. To try it out, build gopls from master and use the "Show type hierarchy" item on the context menu.  Also, we just changed the behavior of "Go to implementations" so that it reports interface/subinterface relationships. Both of these changes should make it easier to navigate type relationships.

**Comment by fengzhongmanbu** [comment]
@adonovan When will this feature be adapted？

**Comment by adonovan** [comment]
> When will this feature be adapted？

As soon as we have a design, and implementing becomes a priority. Less flippantly: it is unclear how to implement this feature so that it is both correct and efficient, which is our usual bar; we really don't want to present incorrect or stale data in the UI. If we had a design, there would be more enthusiasm for implementing it; this feature certainly garners lots of interest.

**Comment by ufukty** [comment]
I noticed that since the first time I visit this feature request and left an upvote, my opinion has changed. Thinking about fake conformances caused by interfaces from different dependencies happen to fully or partially share same method list; developers are already better be leaving conformance assertions like below to notify future maintainers on what interfaces the type needs to keep conforming in future. Isn't the need for this feature narrows down enough to make it a niche after adopting such behavior?

```go
type h string
func (h) ServeHTTP(w http.ResponseWriter, r *http.Request)
var _ http.Handler = h("") // conformance assertion
```

**Comment by fengzhongmanbu** [comment]
@adonovan 

> As soon as we have a design, and implementing becomes a priority. Less flippantly: it is unclear how to implement this feature so that it is both correct and efficient, which is our usual bar; we really don't want to present incorrect or stale data in the UI. If we had a design, there would be more enthusiasm for implementing it; this feature certainly garners lots of interest.

Thanks for the reply, but I think there are already plugins that implement this feature, why not consider their implementation? such as tooltitude.

**Comment by ocean2811** [comment]
For VS Code, I recommend using the `GoGo CodeLens` extension to achieve these Code Lens features. It provides similar functionality to `Tooltitude` while being ​completely free.

Note:​​ `GoGo CodeLens` is a third-party extension. You should ​conduct your own security review​ and determine if it's suitable for your use.

**Comment by anirudhagarwal365** [comment]
I have tried to create something very similar to what GoLand provides - **[Go Implementation Lens](https://marketplace.visualstudio.com/items?itemName=AnirudhAgarwal.go-implementation-lens)**

Do give it a try out. Have also implemented caching for faster lookups. Do give it a try and will be very actively resolving any issues reported.

**Comment by fengzhongmanbu** [comment]
> For VS Code, I recommend using the GoGo CodeLens extension to achieve these Code Lens features. It provides similar functionality to Tooltitude while being ​completely free.

Note:​​ GoGo CodeLens is a third-party extension. You should ​conduct your own security review​ and determine if it's suitable for your use.

@ocean2811  Thanks, I used the plugin you mentioned, but it consumes too many resources. When I open large projects (like the Kubernetes source code), it uses a lot of CPU, causing my computer to freeze.

**Comment by fengzhongmanbu** [comment]
> I have tried to create something very similar to what GoLand provides - [Go Implementation Lens](https://marketplace.visualstudio.com/items?itemName=AnirudhAgarwal.go-implementation-lens)

Do give it a try out. Have also implemented caching for faster lookups. Do give it a try and will be very actively resolving any issues reported.

@anirudhagarwal365 Thanks, I used the plugin you mentioned, but it provides some simple functions. I hope it can provide methods to view struct instance implementations, the number of implemented interfaces, and when clicking on code lens, these results can be opened in a new page, similar to how gopls in VSCode shows all implementations. This way, after viewing a specific implementation, you can close the already viewed results.
Note: You can refer to the implementation results of tooltitude below

**Comment by hedongyouxia** [comment]
> I have tried to create something very similar to what GoLand provides - [Go Implementation Lens](https://marketplace.visualstudio.com/items?itemName=AnirudhAgarwal.go-implementation-lens)

Do give it a try out. Have also implemented caching for faster lookups. Do give it a try and will be very actively resolving any issues reported.

@anirudhagarwal365 Thanks, I used the plugin you mentioned, but it provides some simple functions. I hope it can provide methods to view struct instance implementations, the number of implemented interfaces, and when clicking on code lens, these results can be opened in a new page, similar to how gopls in VSCode shows all implementations. This way, after viewing a specific implementation, you can close the already viewed results.
Note: You can refer to the implementation results of tooltitude below

**Comment by hedongyouxia** [comment]
> I have tried to create something very similar to what GoLand provides - [Go Implementation Lens](https://marketplace.visualstudio.com/items?itemName=AnirudhAgarwal.go-implementation-lens)

Do give it a try out. Have also implemented caching for faster lookups. Do give it a try and will be very actively resolving any issues reported.

@anirudhagarwal365 Thanks, I used the plugin you mentioned, but it provides some simple functions. I hope it can provide methods to view struct instance implementations, the number of implemented interfaces, and when clicking on code lens, these results can be opened in a new page, similar to how gopls in VSCode shows all implementations. This way, after viewing a specific implementation, you can close the already viewed results.
Note: You can refer to the implementation results of tooltitude below

**Comment by anirudhagarwal365** [comment]
> > I have tried to create something very similar to what GoLand provides - [Go Implementation Lens](https://marketplace.visualstudio.com/items?itemName=AnirudhAgarwal.go-implementation-lens)
> 
> Do give it a try out. Have also implemented caching for faster lookups. Do give it a try and will be very actively resolving any issues reported.
> 
> [@anirudhagarwal365](https://github.com/anirudhagarwal365) Thanks, I used the plugin you mentioned, but it provides some simple functions. I hope it can provide methods to view struct instance implementations, the number of implemented interfaces, and when clicking on code lens, these results can be opened in a new page, similar to how gopls in VSCode shows all implementations. This way, after viewing a specific implementation, you can close the already viewed results. Note: You can refer to the implementation results of tooltitude below

@hedongyouxia Clicking on the code lens already does open up in a new tab. If there are multiple implementations, it shows up the list. 

Looks like you were trying to attach something for reference - that is not showing up in your comment. 

Would love to work on something to make it simpler for everyone.

**Comment by hedongyouxia** [comment]
@anirudhagarwal365 I means if the interface have multiple implementations，it show the list in new tab as gopls refrence result，and the plugin can support refrence and methods，it also useful.

<img width="1910" height="1013" alt="Image" src="https://github.com/user-attachments/assets/10a9ef9e-0e5c-4075-8f9f-0905c8b14f2b" />

**Comment by fengzhongmanbu** [comment]
@anirudhagarwal365 What I mean is that if an interface has multiple implementations, clicking the code lens should display results similar to those of gopls querying all implementations (in a new tab, allowing operations like closing), and also whether it's possible to add a code lens for references and interface methods, which would be very useful.

**Comment by fengzhongmanbu** [comment]
@anirudhagarwal365 Sorry，my network have some problem for upload a picture.

<img width="1903" height="1009" alt="Image" src="https://github.com/user-attachments/assets/6a86f0af-b0fb-4102-b037-beab4501ee16" />

**Comment by anirudhagarwal365** [comment]
Oh wow. This makes it very clear. This looks like a pretty neat setup. Lemme see what all I can pick up. Thanks for the feedback though. 

Also, looks like this is an extension that you are using. If you don't mind - can you share the name of this? What do you expect my extension to provide that the one that you have shared a screenshot of, does not have?

**Comment by fengzhongmanbu** [comment]
@anirudhagarwal365 I use the plugin is Tooltitude for Go (GoLang),it not support the interface code lens in vendor or mod pkg and it not free.

**Comment by anirudhagarwal365** [comment]
Hi @hedongyouxia 
I have updated the extension with the changes that you proposed. Please go through the readme file to see a list of changes made. Also, more feedback is always welcome.

**Comment by anirudhagarwal365** [comment]
@adonovan Would you also mind giving this extension a try - [Go Implementation Lens](https://marketplace.visualstudio.com/items?itemName=AnirudhAgarwal.go-implementation-lens)

Would love to hear your feedback on the product and see if this is what you had in mind? 

I had been missing this feature since I moved from GoLand to VSC. I am willing to put in the effort to solving this problem for everyone in the best possible way.

**Comment by adonovan** [comment]
> @adonovan Would you also mind giving this extension a try - [Go Implementation Lens](https://marketplace.visualstudio.com/items?itemName=AnirudhAgarwal.go-implementation-lens)
> Would love to hear your feedback on the product and see if this is what you had in mind?

I haven't run the code, but it appears to [loop over all the symbols in the document](https://github.com/anirudhagarwal365/go-implementation-lens/blob/main/src/goAnalyzer.ts#L93) and make `implementations` and `references` queries to gopls for each one. That won't scale well for large documents and large workspaces.

**Comment by anirudhagarwal365** [comment]
> I haven't run the code, but it appears to [loop over all the symbols in the document](https://github.com/anirudhagarwal365/go-implementation-lens/blob/main/src/goAnalyzer.ts#L93) and make implementations and references queries to gopls for each one. That won't scale well for large documents and large workspaces.

Thanks for taking a look. I have been testing it with my internal codebase which is moderately sized (not super large) and seems to work fine. There's a delay the first time a time is opened and after that I cache the results but I see your point as well. If possible - could you point me in the right direction to solve this? Are you thinking about generating a dependency tree on top of what is present in the language server and power these indicators or something completely different?

**Comment by adonovan** [comment]
> If possible - could you point me in the right direction to solve this? Are you thinking about generating a dependency tree on top of what is present in the language server and power these indicators or something completely different?

As I mentioned in https://github.com/golang/go/issues/56695#issuecomment-3024009745, we don't have a design in mind, but we do have a requirement that it must be scalable. This means the implementation must either return stale and/or heuristic results (allowing it to avoid type checking), or will require building new invalidation mechanisms into gopls.

**Comment by findleyr** [comment]
@anirudhagarwal365 you mentioned that you miss this feature from Goland. Can you say more about what you use it for? VS Code provides a way to find implementations, references, and implementors. Furthermore, it highlights unused (unexported) symbols with a diagnostic. What is it about seeing the number of references or implementations as a code lens that is useful?

(This is not meant to be snarky: there are clearly a large number of users who agree; I am just genuinely curious because I've never wanted this feature myself).

I can see the use case for a code lens that highlights the primary interface implemented by a concrete type, though I think an inlay hint or explicit Go comment may be a better UI for this. However, I don't understand the use case for listing "9 refs" or "3 interfaces" -- it just seems distracting to me; the information is available if I want it...

**Comment by anirudhagarwal365** [comment]
@adonovan Thanks for pointing me specifically to scalability. Don't really have anything right now - lemme check what I am able to come up with.

**Comment by anirudhagarwal365** [comment]
@findleyr I have found seeing the implementation indicators in the gutter icons in GoLand (as posted in the issue) extremely helpful. 
Few reasons worth mentioning - 

1. Not specifically for GoLang - but languages like java provide function overriding - and it is extremely helpful to know if this particular function is actually overridden or written fresh. 
2. For interfaces, it is useful to see how many current implementations are present for this interface. Having one implementation mostly points me to a concrete implementation. 
3. For implemented methods - It is extremely helpful to first check if this function is being implemented from an interface and I would have to think about other places before actually changing it's signature. 

References are generally very helpful when it comes to spaghetti codebases - where there is no clear single responsibility of  functions/methods so you need to get a sense of how widespread the change would be and it's regression impact. 

> VS Code provides a way to find implementations, references, and implementors

Yes it does, but I feel that it is not very indicative in nature. This is an effort to make it more "in the face". 

>  I think an inlay hint or explicit Go comment may be a better UI for this

No arguing here. That actually might work as well - but would lose the capability to click.

**Comment by adonovan** [comment]
> This is an effort to make it more "in the face".

The feature's default keybinding in VS Code is very obscure, and requires a four-key two-handed chord on a mac.

Try the following in VS Code:

- Type Command-Shift-P then "Preferences: Open Keyboard Shortcuts"
- Search for "Go to Implementations".
- Click on the Keybinding cell.
- Type Command-' then Enter.

Now, in your Go source, once your cursor is over a type name, you can type Command-' to instantly see the list of matching types (or jump to the sole entry). If you don't like the jumping behavior, bind this key to Peek Implementations instead. Or to "Types: Show Type hierarchy" to use the side panel. Force yourself to use the feature a few times and see whether it becomes part of your routine, as it has mine.

**Comment by hu3bi** [comment]
The advantage of always directly seeing the overlay like here https://github.com/tkgalk/go-interface-annotations is really nice. 
Especially when looking at a new codebase.

----

That way, it is clear whether removing/renaming a func would break an interface.
- Yes, that could also be achieved by `var _ AnInterface = (*ThisIsAType)(nil)` .
But in the age of AI and coming in and fixing stuff from less experienced people I cannot rely on for this line to be present.

- IDE warnings can alert one to interface violations. However, it would be slightly slower than seeing it up front. And this might not find all no longer implemented interfaces during compile time.

---
**Looking at [https://github.com/tkgalk/go-interface-annotations](https://github.com/tkgalk/go-interface-annotations):**
If this feature can be done in a cheap way it would be nice. If it couldn't be done, for me, it would only be a very minor inconvenience.

**Comment by firelizzard18** [comment]
@hu3bi Counting how many implementations there are in a way that performs reasonably well (when you're running it on every struct/interface in a file) for large projects is not easy. That extension calls "Find implementations" on literally every struct and interface in a file. On a large project where the "Find implementations" function is expensive, `go-interface-annotations` is likely to perform badly (so it's not viable as a solution for vscode-go).
