### ISSUE TITLE
x/tools/gopls: investigate possible slowdown caused by exclusive type checking

### ISSUE THREAD

**Issue by findleyr** [golang/go#62493]
Reported by @leitzler in slack: https://go.dev/cl/511435 may have caused increased latency in large codebases.

Needs additional investigation before the next release.

**Comment by khanakia** [comment]
I do not have a large codebase but still, it's taking around 500ms to autocomplete

![Screenshot_2023-09-07_at_3 58 00_PM](https://github.com/golang/go/assets/2174170/a124b963-703d-45d3-b647-239f9c16c9af)

Any idea how to fix this i am using `vscode`

**Comment by findleyr** [comment]
@khanakia can you share the rest of that trace? It looks like you are only showing the first six lines, but there should be a lot more.

Completion can take a while in very large packages, even in small codebases.

**Comment by khanakia** [comment]
I have uploaded the trace results here let me know if you need anything else

https://github.com/khanakia/entgo_autocomplete_vscode_slow/blob/main/completion.Completion.txt
https://github.com/khanakia/entgo_autocomplete_vscode_slow/blob/main/trace.txt

**Comment by findleyr** [comment]
Thanks. From that trace I can see that type-checking is actually fast: the slowest "forEachPackage" is 50ms.

Therefore, it must simply be the completion logic that is slow, which can happen if it is formatting a very large number of results. I think we can improve this massively, by restricting the number of results and/or delaying the formatting of the completion item (using new LSP APIs).

**Comment by khanakia** [comment]
I see but vs code autocompletion takes around 300 - 500 ms  to show the results in the autocomplete dropdown

The functions I am using come from this file and I do not think it is that big https://github.com/khanakia/entgo_autocomplete_vscode_slow/blob/main/ent/item_create.go

**Comment by findleyr** [comment]
Understood. Thanks for sharing the example. I mean that I think we can actually fix this -- there is nothing making this unsolvable (for example type checking taking too long).

**Comment by findleyr** [comment]
@khanakia  could you try with gopls@master? I believe you may be running into golang/go#/62665, which was just fixed.

To install gopls@master:
```
git clone go.googlesource.com/tools
cd tools/gopls
go install
```

**Comment by findleyr** [comment]
@leitzler could you (1) try out master, and confirm that you still have problems, and then (2) try out https://go.dev/cl/531459, to see if it resolves your problems?

**Comment by khanakia** [comment]
It's way better now auto completion requests are around 110ms for my code base.

**Comment by leitzler** [comment]
Yes! It still exist in master (a slightly old one - `4b34fbf5f10d`) where I see multiple calls taking more than 2 seconds.
Applying CL 531459 solves the issue completely, those calls now takes <20ms.
Thank you!

**Comment by findleyr** [comment]
@khanakia that's good to hear. Thanks for confirming!

@leitzler thanks, it looks like that commit includes https://go.dev/cl/530599, which is what I wanted to check.

Ok, looks like my small CPU optimization was a major latency regression. I'll submit the revert. Glad we caught this before releasing -- thanks!

**Comment by erdauletbatalov** [comment]
Hello @findleyr, I recently got a bug because of your latest gopls version https://github.com/golang/tools/releases/tag/gopls%2Fv0.14.0-pre.1
It causes to code colorization provided by go nightly to disappear. I got used to it because it is very handy. Noticed when I go back to gopls v0.13.2 this feature shows again.
