### ISSUE TITLE
Go 1.25: auto-downloaded toolchain fails to find `covdata` when `go test` run against package with no test files

### ISSUE THREAD

**Issue by mikeauclair** [golang/go#75031]
### Go version

go version go1.25.0 linux/amd64

### Output of `go env` in your module/workspace:

```shell
AR='ar'
CC='gcc'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_ENABLED='1'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
CXX='g++'
GCCGO='gccgo'
GO111MODULE=''
GOAMD64='v1'
GOARCH='amd64'
GOAUTH='netrc'
GOBIN=''
GOCACHE='/home/mauclair/.cache/go-build'
GOCACHEPROG=''
GODEBUG=''
GOENV='/home/mauclair/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFIPS140='off'
GOFLAGS=''
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/home/mauclair/tmp/go-build2752909789=/tmp/go-build -gno-record-gcc-switches'
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMOD='/home/mauclair/go/src/github.com/mikeauclair/toolchain_covdata_replicate/go.mod'
GOMODCACHE='/home/mauclair/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/mauclair/go'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/mauclair/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64'
GOSUMDB='sum.golang.org'
GOTELEMETRY='local'
GOTELEMETRYDIR='/home/mauclair/.config/go/telemetry'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/mauclair/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.linux-amd64/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.25.0'
GOWORK=''
PKG_CONFIG='pkg-config'
```

### What did you do?

Ran `go test -cover` on a package with no test files (with a go 1.25 toolchain downloaded automatically)

### What did you see happen?

```
# github.com/mikeauclair/toolchain_covdata_replicate
go: no such tool "covdata"
```

### What did you expect to see?

```
        github.com/mikeauclair/toolchain_covdata_replicate              %
```

**Comment by mikeauclair** [comment]
I pushed up a quick replication case here https://github.com/mikeauclair/toolchain_covdata_replicate, showing that this works with a system-installed version of go and only seems to fail with the auto-downloaded toolchain

**Comment by trym-moeller** [comment]
It can be noted that manually running `go env -w GOTOOLCHAIN=go1.25.0+auto` fixed a similar problem for me.

**Comment by jerbob92** [comment]
> It can be noted that manually running `go env -w GOTOOLCHAIN=go1.25.0+auto` fixed a similar problem for me.

Thank you, I can confirm that this workaround works!

**Comment by sanmuny** [comment]
Upgrading system go version to 1.25 worked for me as well.

``` bash
brew update && brew upgrade
```

**Comment by wafer-bw** [comment]
> Upgrading system go version to 1.25 worked for me as well.
> ```sh
> brew update && brew upgrade
> ```

I'm still seeing this while running `go test -covermode=atomic ./...` on `go version go1.25.1 darwin/arm64` which is the latest version listed [here](https://go.dev/dl/) at the time of writing this comment.

**Comment by adidyc** [comment]
Hey folks, any updates on this?

**Comment by bschaatsbergen** [comment]
This feels like a toolchain quirk to me; just sharing my thinking and how we addressed it. We were able to work around it by forcing `GOTOOLCHAIN` to match the version specified in `go.mod`.

I suspect that when Go automatically downloads toolchains to resolve version mismatches between local environments and the `go.mod` `toolchain` directive, it fetches a minimal toolchain runtime that lacks certain tools, either due to a bug or by design (not sure which). In our case, the auto-downloaded Go 1.25.4 toolchain was missing the `covdata` tool, causing a CI job to fail with no such tool `"no such tool 'covdata'"` errors (because we rely on `go test -coverprofile`. 

Setting `GOTOOLCHAIN` to match the version in `go.mod` appears to make Go use a complete, locally installed toolchain with all required tools, including `covdata`.

We now rely on the following in our `Makefile` to force this:
```
# Adapted from etcd-operator and k/k:
# Set the GOTOOLCHAIN to force the toolchain defined in go.mod
GOTOOLCHAIN ?= auto
ifeq (auto,$(GOTOOLCHAIN)) # User didn't specify the GOTOOLCHAIN, or is set to auto.
ifeq (,$(FORCE_HOST_GO)) # User didn't provide FORCE_HOST_GO, use go.mod's toolchain
    export GOTOOLCHAIN=$(shell grep '^toolchain go' go.mod | cut -d' ' -f2)
else # User provided FORCE_HOST_GO, use the local version
    export GOTOOLCHAIN=local
endif
endif
```

The etcd-operator team, among others, encountered the same issue and resolved it similarly: https://github.com/etcd-io/etcd-operator/pull/196#issuecomment-3250392465
