### ISSUE TITLE
x/tools/gopls: `//go:fix inline` is very slow to compute fixes (excessive scans of Info.Uses and re-formatting/parsing of whole file)

### ISSUE THREAD

**Issue by connorszczepaniak-wk** [golang/go#75773]
### gopls version

```
Build info
----------
golang.org/x/tools/gopls v0.19.1
    golang.org/x/tools/gopls@v0.19.1 h1:Yodhp3rnpnag60lVZrYPYbGMxTlTCIAj/B2Rv7AKuhA=
    github.com/BurntSushi/toml@v1.4.1-0.20240526193622-a339e1f7089c h1:pxW6RcqyfI9/kWtOwnv/G+AzdKuy2ZrqINhenH4HyNs=
    github.com/fatih/camelcase@v1.0.0 h1:hxNvNX/xYBp0ovncs8WyWZrOrpBNub/JfaMvbURyft8=
    github.com/fatih/gomodifytags@v1.17.1-0.20250423142747-f3939df9aa3c h1:dDSgAjoOMp8da3egfz0t2S+t8RGOpEmEXZubcGuc0Bg=
    github.com/fatih/structtag@v1.2.0 h1:/OdNE99OxoI/PqaW/SuSK9uxxT3f/tcSZgon/ssNSx4=
    github.com/google/go-cmp@v0.6.0 h1:ofyhxvXcZhMsU5ulbFiLKl/XBFqE1GSq7atu8tAmTRI=
    golang.org/x/exp/typeparams@v0.0.0-20250218142911-aa4b98e5adaa h1:Br3+0EZZohShrmVVc85znGpxw7Ca8hsUJlrdT/JQGw8=
    golang.org/x/mod@v0.25.0 h1:n7a+ZbQKQA/Ysbyb0/6IbB1H/X41mKgbhfv7AfG/44w=
    golang.org/x/sync@v0.15.0 h1:KWH3jNZsfyT6xfAfKiz6MRNmd46ByHDYaZ7KSkCtdW8=
    golang.org/x/telemetry@v0.0.0-20250417124945-06ef541f3fa3 h1:RXY2+rSHXvxO2Y+gKrPjYVaEoGOqh3VEXFhnWAt1Irg=
    golang.org/x/text@v0.26.0 h1:P42AVeLghgTYr4+xUnTRKDMqpar+PtX7KWuNQL21L8M=
    golang.org/x/tools@v0.34.1-0.20250610205101-c26dd3ba555e h1:XnjOegqwH6kBJoae6InSGbIFPHcLtUT/Eq8HjrZKbmQ=
    golang.org/x/vuln@v1.1.4 h1:Ju8QsuyhX3Hk8ma3CesTbO8vfJD9EvUBgHvkxHBzj0I=
    honnef.co/go/tools@v0.7.0-0.dev.0.20250523013057-bbc2f4dd71ea h1:fj8r9irJSpolAGUdZBxJIRY3lLc4jH2Dt4lwnWyWwpw=
    mvdan.cc/gofumpt@v0.7.0 h1:bg91ttqXmi9y2xawvkuMXyvAA/1ZGJqYAEGjXuP0JXU=
    mvdan.cc/xurls/v2@v2.6.0 h1:3NTZpeTxYVWNSokW3MKeyVkz/j7uYXYiMtXRUfmjbgI=
go: go1.24.4
```

### go env

```shell
AR='ar'
CC='cc'
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_ENABLED='1'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
CXX='c++'
GCCGO='gccgo'
GO111MODULE='on'
GOARCH='arm64'
GOARM64='v8.0'
GOAUTH='netrc'
GOBIN=''
GOCACHE='/Users/connorszczepaniak/Library/Caches/go-build'
GOCACHEPROG=''
GODEBUG=''
GOENV='/Users/connorszczepaniak/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFIPS140='off'
GOFLAGS=''
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/14/dl88pgbs11766nqnslc5ry8h0000gs/T/go-build730488648=/tmp/go-build -gno-record-gcc-switches -fno-common'
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMOD='/path/to/project/go.mod'
GOMODCACHE='/Users/connorszczepaniak/go/pkg/mod'
GONOPROXY='github.com/Workiva'
GONOSUMDB='github.com/Workiva'
GOOS='darwin'
GOPATH='/Users/connorszczepaniak/go'
GOPRIVATE='github.com/Workiva'
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/opt/homebrew/Cellar/go/1.25.1/libexec'
GOSUMDB='sum.golang.org'
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/connorszczepaniak/Library/Application Support/go/telemetry'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.25.1/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.25.1'
GOWORK=''
PKG_CONFIG='pkg-config'
```

### What did you do?

I put a `//go:fix inline` annotation on a deprecated function; exact verbiage is changed here but the shape is the same:

```
// Deprecated: Use the new function
// For example: newFunction(a, b, c)
// Or more simply: newFunction()
//
//go:fix inline
```

### What did you see happen?

At usages, I don't see a diagnostic for the `//go:fix inline` nor the code action to inline it (though I do see the code action to inline the call, but I think all function calls get this). I do see the deprecation diagnostic at call sites.

### What did you expect to see?

A diagnostic and a code action to inline the call.

If it matters, this Go module is very large (`go list ./...` tells me there are 1421 packages). The function in question also has 1362 usages.

### Logs

Hmm, I tried to pass a `-logfile` in my nvim config of `gopls` to no avail... Can work on this more if it'll be helpful.

**Comment by adonovan** [comment]
Can you provide an example that reproduces the problem? The analyzer will not suggest fixes for calls where it knows the inlining algorithm cannot succeed, for example when making a cross-package call to a function whose body refers to non-exported symbols. There's no good way for the tools to indicate this information, so the error message is discarded and no fix is offered.

**Comment by connorszczepaniak-wk** [comment]
Yes, I did just manage to come up with a small example that reproduces:

Edit: updated to more minimal example

```go
// main_test.go
package main

import (
	"testing"

	"example.com/test_project/pkg1"
)

// Neither of the following functions show inline diagnostics. If I omit the `t` input 
// to `OldFunction` and `NewFunction`, the diagnostics appear.

func TestSomething(t *testing.T) {
	pkg1.OldFunction(t)
}

func SomethingElse(t testing.TB) {
	pkg1.OldFunction(t)
}
```

```go
package pkg1

import "testing"

//go:fix inline
func OldFunction(t testing.TB) string {
	return NewFunction(t)
}

func NewFunction(t testing.TB) string {
	return OldFunction(t)
}
```

**Comment by adonovan** [comment]
Strange... that did not reproduce the problem for me. I created the files in my working tree, and both gopls (in my editor) and the `inline` command were able to inline both calls to OldFunction:

```
tools$ cat gopls/main_test.go 
// main_test.go
package main_test

import (
	"testing"

	"golang.org/x/tools/gopls/pkg1"
)

// Neither of the following functions show inline diagnostics. If I omit the `t` input to `OldFunction` and `Build`,
// the diagnostics appear.

func TestSomething(t *testing.T) {
	pkg1.OldFunction(t)
}

func SomethingElse(t testing.TB) {
	pkg1.OldFunction(t)
}
tools$ cat gopls/pkg1/pkg1.go 
package pkg1

import "testing"

//go:fix inline
func OldFunction(t testing.TB) string {
	return NewBuilder().WithName("").Build(t)
}

type myBuilder struct {
	name string
}

func NewBuilder() *myBuilder {
	return &myBuilder{
		name: "",
	}
}

func (s *myBuilder) WithName(name string) *myBuilder {
	s.name = name
	return s
}

func (s *myBuilder) Build(testing.TB) string {
	return s.name
}
tools$ go run ./go/analysis/passes/inline/cmd/inline/main.go -fix -diff  ./gopls/
--- /Users/adonovan/x/tools/gopls/main_test.go (old)
+++ /Users/adonovan/x/tools/gopls/main_test.go (new)
@@ -11,9 +11,9 @@
 // the diagnostics appear.
 
 func TestSomething(t *testing.T) {
-	pkg1.OldFunction(t)
+	pkg1.NewBuilder().WithName("").Build(t)
 }
 
 func SomethingElse(t testing.TB) {
-	pkg1.OldFunction(t)
+	pkg1.NewBuilder().WithName("").Build(t)
 }
tools$ 
```

**Comment by connorszczepaniak-wk** [comment]
Yes, sorry about that, I _am_ seeing diagnostics in my test module now -- perhaps I was too impatient before or something in my editor was wrong.

I've attempted to more faithfully recreate the exact code from the original module into my small test module and so far have had no luck reproducing the issue. Of note, I created some dummy packages to simulate some of the dependencies from the real function signatures. I wonder if a different import graph could affect things?

Also notably I haven't yet attempted to recreate the same imports/dependencies from the body of the `Build` function, could that affect the decision to suggest inlining?

Here's looking at it from a different angle: in the original module, in the package containing both the old and new functions, I can reproduce with some empty functions:

<img width="387" height="152" alt="Image" src="https://github.com/user-attachments/assets/dfe70e1e-34da-425c-af21-1fcf94a52272" />

Whereas in my small test module, this produces diagnostics:

<img width="810" height="428" alt="Image" src="https://github.com/user-attachments/assets/b879500e-2f6c-48c4-aa7c-b7c54f85de64" />

**Comment by adonovan** [comment]
I believe there is a problem here, and I think I have seen something similar myself, but we need a reproducible test case to proceed.

One hypothesis in my case: when I git-diff a file foo.go, my editor (emacs) creates a temporary file called something like `foo.go.~a3874ef5~` in the same directory that then becomes part of the package, causing it to have compile errors.

**Comment by connorszczepaniak-wk** [comment]
Understood. I have done some more playing around; I still don't have a reproducible test case, but I did try two things with interesting results:
1. Using vscode instead, I'm seeing diagnostics eventually show up
2. In vscode, once I got diagnostics to show up, I see that `gofix` took almost a minute via the gopls debug interface; here are the top few analyzers and their timings:
    ```
    Analyzer.Run times
    52.702523549s gofix
    2.406025874s S1038
    2.043776959s buildssa
    1.524995708s isgenerated
    ```

No amount of waiting in neovim produces diagnostics, so perhaps the issue there is that there's a timeout on LSP requests that differs from vscode.

Perhaps the question now is: why is gofix this slow? Is there more logging or other information I could provide to help diagnose that? It looks like this is at least fairly reproducible and I can see long-running traces for `server.diagnose` from gopls that I could look into sharing if that would be helpful.

**Comment by connorszczepaniak-wk** [comment]
Also: running `go run golang.org/x/tools/go/analysis/passes/inline/cmd/inline@latest` on the single package that produced the above `gopls` results also takes around a minute on my machine. I'm able to grab a CPU profile easily here, which I could also share.

_Edit to include flamegraph_: it looks like `soleUse` is the primary offender here, accounting for more than half the runtime. From a quick glance at the code, it seems like this function might get called for each import of the file containing each callsite of the function to be inlined (possibly even if there are multiple callsites in the same file); it seems like this may just scaling poorly when a function marked for inlining is called a lot, particularly when there are lots of imports in calling files?

<img width="1726" height="453" alt="Image" src="https://github.com/user-attachments/assets/0d3882f3-577b-419f-8edd-9b2d0f730bb3" />

**Comment by adonovan** [comment]
Thanks, this is very helpful information. Indeed soleUse should never have been written this way. I'll get it to build an index (or use the typeindex package if available).

**Comment by adonovan** [comment]
@connorszczepaniak-wk Thanks again for reporting this. Now that a putative fix has been merged, if you feel like it, please try out the latest gopls and see whether it helps:
```
$ git clone https://go.googlesource.com/tools
$ cd tools/gopls
$ go install
```

**Comment by connorszczepaniak-wk** [comment]
Awesome, thanks @adonovan. Indeed, `soleUse` vanished from the CPU profile when running the inline analyzer directly:

<img width="1728" height="915" alt="Image" src="https://github.com/user-attachments/assets/98e7fd02-4215-4766-ba4d-f65bd24359f8" />

And within gopls:

<img width="536" height="215" alt="Image" src="https://github.com/user-attachments/assets/575ba7aa-cbee-4310-9168-44db66f3b1e4" />

A huge improvement; I still don't see the diagnostic or code action in neovim, but that's obviously some issue with my LSP configuration there. Thanks for the fix!

**Comment by adonovan** [comment]
Glad your problem is fixed. Still surprised the walltime for inline is so high. Will investigate.

**Comment by adonovan** [comment]
I have failed to observe significant analysis times for `inline` even on fairly large code bases. Do you reliably see such slow times? Are you able to share a test case that reproduces the problem (i.e. is the target code open source)?

**Comment by connorszczepaniak-wk** [comment]
Yes, the setup I've been using while investigating this issue has been quite repeatable (both running `inline` directly and within `gopls`). 

The repo is not open source, but I would be happy to try to provide more information to help the investigation and/or to try to work towards a representative way to reproduce. What would be most helpful?

**Comment by adonovan** [comment]
> The repo is not open source, but I would be happy to try to provide more information to help the investigation and/or to try to work towards a representative way to reproduce. What would be most helpful?

Thanks. Even just a CPU profile would be a good start, if you don't mind sharing one. (A profile mostly contains strings from the executable, but it principle it may have goroutine labels derived from PII, so preview the output of `gunzip -c cpu.prof | strings -` before sharing it.)

**Comment by connorszczepaniak-wk** [comment]
Here are CPU profiles for a few different cases:
- Running `inline` on the single, original package with no `go:fix inline`s of our own [inline_cpu_single_package_before.prof.gz](https://github.com/user-attachments/files/23505494/inline_cpu_single_package_before.prof.gz)
- Running `inline` on the single, original package after adding `go:fix inline` to the function that was the impetus for this issue (maybe interesting because it took almost twice as long) [inline_cpu_single_package_after.prof.gz](https://github.com/user-attachments/files/23505515/inline_cpu_single_package_after.prof.gz)
- Running `inline` on the whole repo, with the added `go:fix inline` mentioned above (took a little less than two minutes) [inline_full_repo_after.prof.gz](https://github.com/user-attachments/files/23505542/inline_full_repo_after.prof.gz)

**Comment by adonovan** [comment]
Thanks. Even with the fix to avoid scanning the Info.Uses map once per import, we're still scanning it much more than necessary. We should do it at most once per package. I'll prepare a fix.

<img width="1178" height="609" alt="Image" src="https://github.com/user-attachments/assets/d9b1ea3f-9104-4493-af7d-640b3c3364ab" />

**Comment by adonovan** [comment]
I just mailed a CL which I hope will make this rather better. If you have a chance, please patch it into your x/tools repo, reinstall gopls, and see if it improves performance in your workspace. Thanks.

**Comment by connorszczepaniak-wk** [comment]
Thanks for your continued investigation. Your CL indeed eliminated the rest of the `newImportState` time from the profile. Most of the rest of the analyzer's direct computation time now is in formatting nodes.

With the patched `gopls`, it looks like this still isn't fast enough for neovim to want to display diagnostics (and I haven't yet spent the time to figure out whether I can configure it so that it will; VSCode eventually does, but it takes ~30 seconds or more for them to appear). I'm not sure if there's anything left here to optimize given what I'm seeing in the profile, but if there's anything more I can provide that would help please let me know.

**Comment by adonovan** [comment]
Studying the profile and the source it seems that the inliner could made be rather more efficient in the way that it splices its changes into the existing file. Currently, it:

- computes a new AST for the CallExpr (or some ancestor)
- formats it, splicing it into the rest of the file (after some fiddling)
- reparses the whole file 
- adds new imports into the new AST
- formats the import decl, splicing it back into the file (after some fiddling)
- reparses the whole file again
- deletes imports of p made redundant by elimination of the call expresson p.F(...)
- formats the whole file yet again

The analyzer then computes the diffs of this result against the original file contents. That means we parse the whole file three times just to offer each fix, which is typically a +/-1 line patch to a callsite. It is easy to see how a single large file containing may inlinable calls leads to a quadratic slowdown.

From first principles, it seems that it should be possible to compute one edit for the replacement of the CallExpr (or its ancestor), and one edit for the import spec, without reparsing or formatting the whole file at all. In fact, we should be able to return TextEdits directly.

Also, deletion of unused imports may now be unnecessary since the analysis drivers do it (as they must, since it's a global property and can't be the responsibility of an analyzer: two fixes might both remove the second-last use of an import).

So I think this code code be massively simplified, and made a lot more efficient. (Of course, this code got the way it is because of various subtleties, so it won't be an easy change, but the test suite should encode many of the constraints.)

**Comment by connorszczepaniak-wk** [comment]
Awesome, it sounds like there's a promising path forward -- if there's any portion of the changes you described that I could help with I'd be happy to contribute!

**Comment by adonovan** [comment]
(Reopening again. We still have work to do.)

**Comment by adonovan** [comment]
I just merged a third change that should (I think) make a significant improvement to performance because it completely removes computation of edits from the fast path: now the edits are computed only when they need to be applied. Please sync to master, reinstall gopls, and let me know once again if this helps. Thanks!

**Comment by connorszczepaniak-wk** [comment]
`inline` is now significantly faster. About 6 seconds to run `inline -lazy_edits ./path/to/pkg`, down from 18-30 seconds from before. In `gopls`, it seems to be even better:

<img width="277" height="323" alt="Image" src="https://github.com/user-attachments/assets/dc8bbbd6-52fa-48de-b46c-e25af5baed1d" />

Weirdly, I still can't get diagnostics to show up in neovim in this particular package/for this function, but of course that's not a gopls problem!

**Comment by adonovan** [comment]
OK, it sounds like the performance problem is resolved, so I'm going to close this issue.

I think you are saying that because the neovim problem is not reproducible in VS Code, it's likely to be an issue with the neovim LSP client. That seems likely, but please do open an issue (or reopen this one) if you think there in in fact a problem on our side.

Thanks again for reporting this. If only all our interlocutors were so helpful!

**Comment by connorszczepaniak-wk** [comment]
@adonovan 💡🤦  to close the loop on the neovim problem: it turns out a neovim plugin was managing a different version of `gopls` than I had installed from `master`, so I was never seeing any of these changes there! I fixed that now, and finally the diagnostics showed up as expected.

Thank you for your work on this!
